### ISSUE TITLE
wxMaxima hangs waiting for Maxima output

### ISSUE THREAD

**Issue by fsobral** [andrejv/wxmaxima#864] opened 2017-03-10 17:37 UTC
I'm using Ubuntu 14.04, 64 bits and updated to wxMaxima 16.12.2-1 recently, using Blahota's **ppa**. Now, I'm unable to create simple expressions like `x + y;`. wxMaxima says that is "Reading output from Maxima", but never returns. The same command works on version 16.10, but not on version 16.12. I'm using Maxima version 5.32.1.

**Comment by gunterkoenigsmann** [comment] 2017-03-12 09:07
Arrgh! That is bad!

And it was reported from 2 computers nearly at the same time. But - on my computer it works fine. It is 64 bits, too - so there needs to another difference between out systems. 

Are you sure wxMaxima did actually start maxima?

With a lot of luck the problem is resolved in the packages from https://code.launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies, - even that doesn't really solve the problem, unfortunately.

**Comment by fsobral** [comment] 2017-03-21 21:06
Thanks for the answer.
I've confirmed that maxima was started. Using the suggested ppa fixed my problem, but rolling back to official version 13.04.2-2 also fixed it.

**Comment by gunterkoenigsmann** [comment] 2018-01-27 15:51
Revised the communication between maxima and wxMaxima. I believe the problem is finally solved in the current release.

**Closed by gunterkoenigsmann** 2018-01-27 15:51 UTC
