### ISSUE TITLE
wxMaxima archlinux x64

### ISSUE THREAD

**Issue by archbugaboo** [andrejv/wxmaxima#743] opened 2016-07-07 08:05 UTC
Hello

My apologies if I don't quite get this right, new to github. I recently encountered a problem in wxMaxima, archlinux x64, and I let the mainainer know of it [here](https://bugs.archlinux.org/task/49969). It was solved, promptly, but he suggested I'd take this upstream, so here I am.

If this is a wrong message, I am sorry, and please delete it.

**Comment by gunterkoenigsmann** [comment] 2016-07-14 10:57
This ticket is definitively valid - but using the latest nightly build of wxMaxima this problem seems not to be reproducible on my Ubuntu computer. This might mean that we did something that resolved this issue. 

Just in order to make sure that we actually did that: As long as I cannot see where a problem happens there is only a very small possibility that I stumble upon the right place to resolve it. But there might be a way to see where the problem happens on your computer.

If you are willing to help I therefore beg you to do the following:
 - Install gdb
 - Install the debug symbols for wxMaxima (at least I think arch linux splits the debug symbols into a separate package: At least Ubuntu does so; Without debug symbols it is possible to retrieve the information at which address a program crashed. But the information which line number in the code this would be is missing in this case.).
 - open a console and type:

      gdb wxmaxima
      run 

Now open the file and as soon as wxMaxima crashes type the following command into the console:

     backtrace

Normally gdb now should tell us the exact place wxMaxima has crashed at - and which decisions led there... ...when the code lines the problem occurs at are known the rest should be  trivial.

Thanks a lot,
and kind regards,

  Gunter.

**Comment by archbugaboo** [comment] 2016-07-14 18:15
Hello Gunter

I am willing to help, but what you say sounds a lot like what I described for the Archlinux guys, minus the backtrace. I had patience to compile with debugging, then ran it with gdb, and it crashed pointing at MathCell.cpp, tmp->ClearCache(), line ~120~130(?), don't remember this part. At any rate, i'll quote in here what I said there (if you follow the link in the first post, there's also an uploaded file that crashes):
***
Description:

wxMaxima crashes with a segfault when loading older saved files.


Additional info:
* package version(s): 16.04.2-1 x64
* config and/or log files etc: only a segfault


Steps to reproduce:

If opened with a double click or simply "wxmaxima" from the terminal, it complains about an ABI mismatch (1009 vs 1010), it opens up fine, can work with it, can save, both .wxm and .wxmx, can load them, but when I try to load older saves (like the one in the attachment), it crashes with a segfault.
If run from console with "wxmaxima -o Bessel.wxm", there's the same ABI mismatch, then, immediately it crashes and sbcl starts flooding the terminal. I need to "killall -9 sbcl"; there are hundreds, if not thousands of lines in there.

Downgrading to 16.04.0-1 works and seems stable.

This is since the newest upgrade after 16.04.0-1. I went to #archlinux and talked to a few over there, they suggested to build wxMaxima with debugging enabled, I did, with their help I used it with gdb, which pointed to MathCell.cpp, "tmp->ClearCache()", line 100 and something. I don't have the debug version, anymore.

As a side note, the update to wxMaxima came with Codeblocks, as well, which also complained about the same ABI mismatch and crashed immediately with its bug report window. The latest update to CB seems to have the same ABI complaint, but it works now. CB could also be downgraded, but the debugger seemed to take forever for "next instruction". Just so you don't get the wrong ideas, I am only just learning C++...

If there's anything else that I can do, please let me know.

**Comment by gunterkoenigsmann** [comment] 2016-07-14 19:29
Then I am convinced the problem is solved in the current git head - and therefore the problem will no more exist in the next release: A few months ago I have resolved an error that only happened for .wxm files (I personally use .wxmx) and that consisted of MathCell calling a ClearCache on a cell that isn't an image and therefore doesn't have an image cache.

Thanks a lot for being willing to help the arch linux guys and me debug where it can be found!

The problem that sbcl outputs this many messages cannot be fixed on wxMaxima's side. But the current release of sbcl no more has this problem: If wxMaxima crashes the network connection that connecs wxMaxima to sbcl is broken - which causes sbcl to output an error message. Unfortunately the error message is output over the network connection - which no more exists, which causes another error message that....
...in the new version sbcl stops outputting messages to the network if the network no more works.

The ABI mismatch problem sounds like having been caused by the fact that the C++ standard has changed in a way that if you used std::list made you decide which side you are on. Unfortunately wxMaxima is heavily based on lists... ...things like that tend to happen about every 5 years. Let's hope that the next time you won't be among the ones that won't be affected: Until now all of these transitions never caused any trouble for me.

Thanks again,
and kind regards,

   Gunter.

**Closed by gunterkoenigsmann** 2016-07-14 19:29 UTC
