### ISSUE TITLE
Ability to display subscripted variables

### ISSUE THREAD

**Issue by endolith** [andrejv/wxmaxima#373] opened 2014-12-09 03:39 UTC
For subscripted variable names, it is recommended to use something like `%alpha[p]` to display as α<sub><i>p</i></sub>.  Example:

![subscript example](https://cloud.githubusercontent.com/assets/58611/5351866/ccfdd016-7f2a-11e4-9a6c-ab2f0592cb3a.png)

But this isn't a real label subscript; it's a list element.  It can't be used in all the same ways as a variable, for instance [it fails with `depends` or `declare` statements](https://www.ma.utexas.edu/pipermail/maxima/2007/007554.html).

wxMaxima already magically displays `omega` the same way as `%omega`, so can it also display underscores as subscripts in latex style?

Ideally, `omega_L` should be rendered as *ω*<sub>L</sub> with upright subscript to indicate it's a label, while `omega[L]` should be rendered as *ω<sub>L</sub>* with italic subscript, to show that the L is a variable.

In https://github.com/andrejv/wxmaxima/issues/221 it is argued that variables_can_contain_underscores without them being intended as subscripts, which is true.  Maybe there should be a switch to interpret them one way or the other?  Or maybe there is another unambiguous variable name notation that could indicate subscript labels, like `variable_subscript_` with trailing underscore?

Alternatively, is there a way to declare the LaTeX representation of a variable (which will be used both for display and also for "Copy LaTeX", but not for "Copy"), in the same way that [SymPy](http://www.sympy.org/) has `x1 = var('x_1')`, where variable x_1 is pretty-printed as x<sub>1</sub>?

`texput(a, "test");` looks like it is supposed to do this?  But it doesn't seem to work with wxMaxima's rendering, which still says `a` and "Copy LaTeX" still outputs `\[a\]`.  I also found [`wxxmlput` but Andrej says it is "basically useless"](https://www.ma.utexas.edu/pipermail/maxima/2007/007690.html) because it doesn't support copying to clipboard, etc.

**Comment by gunterkoenigsmann** [comment] 2015-02-02 20:54
If I am not completely misleaded this functionality would have to be added to maxima first before wxMaxima can follow. In fact there have been many request in the maxima's mailing list for adding subscripts. But AFAICS until now there were no proposals on the notation how to express subscripts that aren't arrays. If you have a good idea please tell maxima's mailing list and/or report at https://sourceforge.net/p/maxima/bugs/. Will close this bug report for the meantime, but I at least can acknowledge that adding a way to express subscripts in maxima feels like being a good idea to me.

**Closed by gunterkoenigsmann** 2015-02-02 20:54 UTC
Labels: feature request

**Comment by endolith** [comment] 2015-02-02 23:11
> isleaded this functionality would have to be added to maxima first before wxMaxima can follow

The proposal is to add these to WxMaxima, not Maxima.  They would be for display only, like how `omega` displays as "ω".

> But AFAICS until now there were no proposals on the notation how to express subscripts that aren't arrays

`omega_L` should be rendered as *ω*<sub>L</sub> with upright subscript to indicate it's a label, while `omega[L]` should be rendered as *ω<sub>L</sub>* with italic subscript, to show that the L is a variable.

**Comment by andrejv** [comment] 2015-02-03 00:45
I am reluctant to include such changes to wxmaxima since it is a very special case. I often define functions such as `fun_A` and want them to be displayed with the subscript.

There was a bug in the wxxmlput function which I just fixed. If you get `wxmathml.lisp` from git you should be able to do something like

    wxxmlput(%omega_L, "<i altCopy=\"%omega_L\"><g>omega</g><n>L</n></i>");

to get the display you with and you can also copy to clipboard. You can put this into your `wxmaxima-init.mac` file and get the display you wish every time without the need to change the display manually.

**Comment by lvwarren** [comment] 2015-12-04 22:58
how then would you display Δt and have wxmaxima consider it the name of a variable?

**Comment by dilijev** [comment] 2015-12-05 00:00
In the past I've just accepted that this is a limitation of the display and get something close enough, e.g. %Delta_t => Δ<sub>t</sub>

**Comment by lvwarren** [comment] 2015-12-05 03:45
I don't settle for close enough, but thank you for responding. I do appreciate that.

**Comment by lvwarren** [comment] 2015-12-05 04:13
BTW - Using
wxxmlput(%omega_L, "<i altCopy=\"%omega_L\"><g>omega</g><n>L</n></i>");
without the <n>L</n> phrase
causes a reproducible and  fatal crash under MacOSX El Capitan Version 10.11.

**Comment by dilijev** [comment] 2015-12-05 05:40
Not saying we should settle for close enough. I was just hoping to give you a workaround until we have a better option.

**Comment by lvwarren** [comment] 2015-12-05 06:20
![screen shot 2015-12-05 at 12 18 22 am](https://cloud.githubusercontent.com/assets/589358/11606395/bae72242-9ae5-11e5-8c0a-9b6530a44df2.png)
Thanks for the workaround. I got Δt to work properly after some fiddling
It crashes and burns spectacularly unless one leaves the <n> tag in place.

**Comment by gunterkoenigsmann** [comment] 2015-12-05 08:03
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Which version of wxMaxima are you using? I cannot reproduce this on my
Linux PC.

Kind regards,

 Gunter.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQJ8BAEBCgBmBQJWYppYXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOvhcP+QF4dcKzGE3uNCrgT9A1x7pe
kOoBojZkpV45CbltcPgVeZgSTB+cbMifpTQ0o8NznBON9sCXZiLEEQZRF8MHDYE7
x/HSwawmP5VrOr33NC9L9zTB9kAIrOjTCVBIRjqXETQis/mre5MKC0XtpzpBQVDs
oIQsR0+icp3OnylhXqfNU0+sbbAjNjBacABC2fPKd5u+PI7uCQsWGgIjmp87/Gd0
mtz/j8ptUWrt7ob0TYyIqnJDGGSS5W9IbZ2/ZghlgM/hsD0w44LIRn/y66EMC2F1
quojwLpTrOysp1FslU0EeL4tiQRB4eMmdIZ48c4YPh6b8PXOK/lkrAWVzTEsVR43
FcWS6HElk8IAtfanih9xY9ZhQcYdY0PnWbrj+Hu06JYs+/xwOkq9g7tSuAyC6i9V
QJQhpe6egXvQm9KB7bxIKatw/h9OJAeOU/zjIsKv+IdT9oEVn+TCoGCW6qS8GUa8
PccjlON1xjM0K2gt3sZZTPcKshGxFaS6GmmI4bqw02hGAt4XzwhSsJHWlEwiIaU/
V/CLmgD2d8lSah92ftatwRh3NQPR7Waov7ZkIHzD1F2Z3WJmUAMRKXd3bXdyYZGM
ez1oxQS0jcyYw2i/ZsJUgQG71XBiS46dQpRTvHHSQ6Reb/o0wcXu6VeHBFrJsP+a
AUfhYA2cMc9tEkitzCGP
=MZaH
-----END PGP SIGNATURE-----

**Comment by gunterkoenigsmann** [comment] 2015-12-05 08:51
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

wxMaxima gets requests for a way to display subscripts on a regular
basis, too. But I refuse to implement them only on the wxMaxima side:
Implementing features only in one project IMHO would make the two
projects drift away from each other too far.

Kind regards,

   Gunter.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQJ8BAEBCgBmBQJWYqV+XxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOIacP/iG37hmUnmzy6r6tdFO9XsLe
mUuNsXzJlXPCDhxRd2TLxJo7EqX2ni41qmb8jyPI812szJoVM87NYo1+8q23dbUh
P4aNQ/kcUAVPhZhUdV4uz/0I3WkMIAJCBX6h+eFlAI4LjrdBMxRyaFLtLfpLWbad
VmFEt+/7srWkSzPy1hK7n5MBoaSzvQ+0pRL49c6n6NDNDdfbshJTLUmZdCcvkK58
Zs3iC4rqFH/N30sDDYEYudCkqpEt0WN+zcZQgGyd5v8AHRB4GFPJdO4+BzUGNLM3
nilnDnUep6xZcFLJz//NW5awb7Ba5tdvKGzxB0TJ0rKE5SXtHX8ofnW1xU8W1i8d
hyKM5+gd+d2WgCXSOTDoGswV0zub0+XJcCjfMX+FltBvEQkEPur6TxcIOR+9F8Qc
McDORr1iNPGGi4YjgglMKElOIVWHm2yMmjAjivigGS/y4wJ2oefNyTaDyytOrndh
nh+C2ZCN6fOBacCrtPYNYcZJonGmw4AA4ICmjjR5ocAvlfhyegaC+rrnkAHOrS77
os30sXy9sWdi3cKE9OtT+5ax8yLEJLUgT4nmir2omOLcpkEndkLpYCxIhS3M5Bnx
AYMFyqZDogZVn53xkcEj1zHxO76wdti/1SrxQjjMynyRPXdWxEMzomxeUOULOr3Q
qLVUrd9Fi0vEW/MrL+gH
=KKK4
-----END PGP SIGNATURE-----

**Comment by lvwarren** [comment] 2015-12-05 18:32
MacOS ElCapitan10.11 beta. Screen capture to follow.

Sent from Outlook




On Sat, Dec 5, 2015 at 12:03 AM -0800, "Gunter Königsman" <notifications@github.com> wrote:





-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Which version of wxMaxima are you using? I cannot reproduce this on my
Linux PC.

Kind regards,

 Gunter.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQJ8BAEBCgBmBQJWYppYXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOvhcP+QF4dcKzGE3uNCrgT9A1x7pe
kOoBojZkpV45CbltcPgVeZgSTB+cbMifpTQ0o8NznBON9sCXZiLEEQZRF8MHDYE7
x/HSwawmP5VrOr33NC9L9zTB9kAIrOjTCVBIRjqXETQis/mre5MKC0XtpzpBQVDs
oIQsR0+icp3OnylhXqfNU0+sbbAjNjBacABC2fPKd5u+PI7uCQsWGgIjmp87/Gd0
mtz/j8ptUWrt7ob0TYyIqnJDGGSS5W9IbZ2/ZghlgM/hsD0w44LIRn/y66EMC2F1
quojwLpTrOysp1FslU0EeL4tiQRB4eMmdIZ48c4YPh6b8PXOK/lkrAWVzTEsVR43
FcWS6HElk8IAtfanih9xY9ZhQcYdY0PnWbrj+Hu06JYs+/xwOkq9g7tSuAyC6i9V
QJQhpe6egXvQm9KB7bxIKatw/h9OJAeOU/zjIsKv+IdT9oEVn+TCoGCW6qS8GUa8
PccjlON1xjM0K2gt3sZZTPcKshGxFaS6GmmI4bqw02hGAt4XzwhSsJHWlEwiIaU/
V/CLmgD2d8lSah92ftatwRh3NQPR7Waov7ZkIHzD1F2Z3WJmUAMRKXd3bXdyYZGM
ez1oxQS0jcyYw2i/ZsJUgQG71XBiS46dQpRTvHHSQ6Reb/o0wcXu6VeHBFrJsP+a
AUfhYA2cMc9tEkitzCGP
=MZaH
-----END PGP SIGNATURE-----


---

**Comment by lvwarren** [comment] 2015-12-05 18:37
It's time to coordinate. wxMaxima is one of the most important technical softwares in the world. Without it, the selfish corporate interests that control Maple, Mathematica and Mathlab would control the free expression of Mathematics worldwide. There is no one whose work we rely on that us as important or historic as yours.

- Van



On Sat, Dec 5, 2015 at 12:51 AM -0800, "Gunter Königsman" <notifications@github.com> wrote:





-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

wxMaxima gets requests for a way to display subscripts on a regular
basis, too. But I refuse to implement them only on the wxMaxima side:
Implementing features only in one project IMHO would make the two
projects drift away from each other too far.

Kind regards,

   Gunter.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQJ8BAEBCgBmBQJWYqV+XxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOIacP/iG37hmUnmzy6r6tdFO9XsLe
mUuNsXzJlXPCDhxRd2TLxJo7EqX2ni41qmb8jyPI812szJoVM87NYo1+8q23dbUh
P4aNQ/kcUAVPhZhUdV4uz/0I3WkMIAJCBX6h+eFlAI4LjrdBMxRyaFLtLfpLWbad
VmFEt+/7srWkSzPy1hK7n5MBoaSzvQ+0pRL49c6n6NDNDdfbshJTLUmZdCcvkK58
Zs3iC4rqFH/N30sDDYEYudCkqpEt0WN+zcZQgGyd5v8AHRB4GFPJdO4+BzUGNLM3
nilnDnUep6xZcFLJz//NW5awb7Ba5tdvKGzxB0TJ0rKE5SXtHX8ofnW1xU8W1i8d
hyKM5+gd+d2WgCXSOTDoGswV0zub0+XJcCjfMX+FltBvEQkEPur6TxcIOR+9F8Qc
McDORr1iNPGGi4YjgglMKElOIVWHm2yMmjAjivigGS/y4wJ2oefNyTaDyytOrndh
nh+C2ZCN6fOBacCrtPYNYcZJonGmw4AA4ICmjjR5ocAvlfhyegaC+rrnkAHOrS77
os30sXy9sWdi3cKE9OtT+5ax8yLEJLUgT4nmir2omOLcpkEndkLpYCxIhS3M5Bnx
AYMFyqZDogZVn53xkcEj1zHxO76wdti/1SrxQjjMynyRPXdWxEMzomxeUOULOr3Q
qLVUrd9Fi0vEW/MrL+gH
=KKK4
-----END PGP SIGNATURE-----


---
