### ISSUE TITLE
Left click places cursor/caret 1..2 characters off

### ISSUE THREAD

**Issue by MSoegtropIMC** [andrejv/wxmaxima#1012] opened 2018-06-29 16:26 UTC
Dear wxMaxima Team,

not in all, but in many situations wxMaxima places the cursor (caret) 1..2 characters off when a left click in input text is done. I attached an example wxmx file. Clicking on most of the variables "x" in this file places the cursor substantially off. 

E.g. when clicking on the comma in front of the `x` in `,x,a,b` in the integral places the cursor in front of the `a` following it, which is 2.5 characters off.

I am not sure what is required to produce the offset, it might be () or [], not sure. It does not happen in all input, but it happens frequently (for me).

The zip also contains my style ini file, in case this depends on the style.

Best regards,

Michael

[ClickOffset.zip](https://github.com/andrejv/wxmaxima/files/2150107/ClickOffset.zip)

Build info:
```
wxMaxima version: 18.02.0.unofficial
using wxWidgets version: wxWidgets 3.1.0
Maxima version: branch_5_41_base_429_g578b7a0_dirty
Maxima build date: 2018-06-24 23:45:44
Host type: x86_64-w64-mingw32
System type: Win32 10.0.16299 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.4.2
wxMaxima's idea of the directory layout is:
User configuration dir: C:\Users\soegtrop/maxima/
Help dir: C:\bin\maxima-daily\wxMaxima/help
Maxima lisp dir: C:\bin\maxima-daily\bin/../share/maxima/branch_5_41_base_429_g578b7a0_dirty
```

**Comment by gunterkoenigsmann** [comment] 2018-06-29 18:53
I hate errors I cannot reproduce on any of the computers I have access to.
The question now is what is setup differently on our computers.

**Comment by MSoegtropIMC** [comment] 2018-06-30 08:04
@gunterkoenigsmann : will your commit automatically be built in some CI, so that I can download it, or will the next nightly build have it? I can also build it from sources, but it would take a few days until I find time to dig into this.

I tried playing with window layouts, scroll positions and the like but I either always see it for a specific expression or not at all. I can also reproduce this on my workstation and laptop, which are both Windows 10.

**Comment by gunterkoenigsmann** [comment] 2018-06-30 08:58
Seems like Every. Single. Install of Win10 reacts totally different to every other while win7 is just win7 and Linux either has a broken gtk or just works like magic despite being customizable in nearly every aspect...

The commit will be part of the next nightly build on Dautermann.at which has proven to be one of the most important tools for development of wxMaxima.

**Comment by MSoegtropIMC** [comment] 2018-07-02 08:09
I also had some bad experience with Windows 10 - privately I am on Debian but in office it is Windows ...

I tested the nightly build from today (July 2nd). The issue is still there ...

Btw.: I also cleared HKCU/Software/wxMaxima in the registry to see if some odd settings piled up over the years, but this didn't have an effect either. It looked quite different (I guess my styles settings are a bit special) but the effect is exactly the same.

One more note: the offset is mildly zoom dependent. It is by far not proportional (in the sense that the offset is constant in screen pixels) I would say, but when I zoom out, the offset in number of characters gets a bit larger (in really unreadable super tiny, the cursor is behind the b if I click on the comma in front of the x).

One thought: is it possible that this depends on the screen dpis? As far as I can tell there have been substantial changes in screen scaling between Windows 8 and 10, and this would also explain why it is different on different machines. But then the screen scaling should be different on my laptop (15" 1920x1080) and workstation (24" 1920x1200), but the effect is the same. Maybe different scales from different sources are used in different places, and this results in a small scaling dependent offset.

Unfortunately I think there is no (easy) way to change the screen scaling in Windows 10. In Windows 8 one could just adjust it in monitor settings - in Windows 10 it looks like they put in some neural network to figure out the screen scaling - is usually somehow gets it right but it is very hard to find out what exactly it does).

Sorry that I have no better news ...

**Comment by gunterkoenigsmann** [comment] 2018-07-02 10:41
Sooner or later we'll find out where the error lies. Actually you made me find bugs both in the scaling and the redrawing code so we definitively have made the code already better than it was yesterday...

**Comment by gunterkoenigsmann** [comment] 2018-07-03 05:48
In case that the current nightly build still doesn't work: Does the selection start and/or end at the wrong point? Or is it just displayed wrongly?

**Comment by MSoegtropIMC** [comment] 2018-07-03 14:09
@gunterkoenigsmann : the nightly build from today (July 3rd) still doesn't work. But it is good that you make progress - I am happy to test until it is solved.

Let me do the problem description more precise: in the test file I sent, when I click (just click) on the middle of the comma in front of the second x in `integrate((polynom(x,n)-f(x))^2,x,a,b)`, the text cursor is places in front of the a (in very small scaling in front of the b). When I drag select the `x`, the `a` is selected. It is not so that the selection or cursor is displayed wrongly, it is so that the selection is wrong. E.g. when I drag select the `x`, so that `a` is selected, all other `a` in the file are highlighted.

Best regards,

Michael

**Comment by richardgobeli** [comment] 2018-07-04 20:20
It is possible scaling from mouse click to line position.  The offset gets bigger the closer I get to the end of the line.  It is easy to see by clicking at the beginning and hold the button while moving the  mouse to the left.   The  selection position slowly advances a head of the  mouse position.  By the end of the line,  the selection is  two or three characters ahead of mouse position.  
The offset looks like it is a bit to the left a the beginning of the line.

**Comment by richardgobeli** [comment] 2018-07-04 23:11
There is something on the integrate line that can't be seen.  If I type the line it works OK.  If I copy the line into another window it has the scale offset.

**Comment by MSoegtropIMC** [comment] 2018-07-05 07:56
@richardgobeli : what happens if you type the line and execute it?

I don't think it is an effect of my specific settings. I cleared the registry of wxMaxima which restores default settings and the effect is still there.

**Comment by gunterkoenigsmann** [comment] 2018-07-05 11:37
Drawing and selecting text both measure the text widths independently: Drawing of one colored text chunk at a time, selecting instead needs to determine the line width of the first n characters of the line until the cursor is reached. What I have already tried to fix:

 - Make sure that both steps use the same font.
 - Make sure they both use the non-antialiasing graphics context: The aliasing one on Windows only supports half of the installed fonts ;-(
 - Today's change: Measure the text widths snippet-per-snippet and only char by char within the snippet the cursor is in.

If this doesn't work the "view/debug messages" pane might tell us more tomorrow.

**Comment by gunterkoenigsmann** [comment] 2018-07-09 19:56
I have finally managed to reproduce something that looks like your initial description. My commit from today resolves this issue => With a bit of luck tomorrow's nightly build will work flawlessly.

**Comment by MSoegtropIMC** [comment] 2018-07-11 09:46
@gunterkoenigsmann : many thanks, in the daily build from this morning the issue is indeed fixed.

**Closed** 2018-07-11 09:46 UTC

**Comment by gunterkoenigsmann** [comment] 2018-07-11 21:18
Many thanks for you for all the testing: As the problem wasn't reproducible on my computer all attempts on fixing the issue depended on your help this time.
