### ISSUE TITLE
Malformed XML from maxima

### ISSUE THREAD

**Issue by brettsbh** [andrejv/wxmaxima#772] opened 2016-09-30 15:01 UTC
Hello, I have a problem with this file (I know about depends() and linel()). The last step, factor() seems to cause a bug, repeatedly. If it helps to know, there are several covering sheets "rho" that can take either of two positions, zeta1 and zeta2, in a local coordinate system, to track two points being covered. I had thought of indexing rho as just one function but rho1 and rho2 seems to work, though in the future I'll need to consider more rho's.... Anyway....

It does work in Maxima by the way, even with the Greek letters. It outputs the derivatives with a single quote before them. Maybe here is the problem... 

/***************************/
reset();
kill(all);

llinel:244$

ddepends(ρ1,[ζ1,ζ2]);
ddepends(ρ2,[ζ1,ζ2]);

h(zeta,rho,Q):=1-Q_rho^2-zeta_rho*(1-rho^2);

print("A__ = h_{2,1}^{(1,0)}(ζ_k,ρ_1^{(k)})")$
print("B__ = h_{2,1}^{(1,0)}(ζ_l,ρ_2^{(l)})")$
print("C__ = h_{2,1}^{(0,1)}(ζ_k,ρ_1^{k)})")$
print("D__ = h_{2,1}^{(0,1)}(ζ_l,ρ_2^{l)})")$

print("k=1,l=1")$

A11: diff( h(ζ1,ρ1(ζ1),Q) ,ζ1)$ expand(%);

B11: diff( h(ζ1,ρ1(ζ2),Q) ,ζ1)$ expand(%);

C11: diff( h(ζ1,ρ1(ζ1),Q) ,ρ1(ζ1))$ expand(%);

D11: diff( h(ζ1,ρ1(ζ2),Q) ,ρ1(ζ2))$ expand(%);

print("k=1,l=2")$

A12: diff( h(ζ1,ρ1(ζ1),Q) ,ζ1)$ expand(%);

B12: diff( h(ζ2,ρ2(ζ2),Q) ,ζ2)$ expand(%);

C12: diff( h(ζ1,ρ1(ζ1),Q) ,ρ1(ζ1))$ expand(%);

D12: diff( h(ζ2,ρ2(ζ2),Q) ,ρ2(ζ2))$ expand(%);

print("k=2,l=1")$

A21: diff( h(ζ2,ρ2(ζ1),Q) ,ζ2)$ expand(%);

B21: diff( h(ζ1,ρ1(ζ2),Q) ,ζ1)$ expand(%);

C21: diff( h(ζ2,ρ2(ζ1),Q) ,ρ2(ζ1))$ expand(%);

D21: diff( h(ζ1,ρ1(ζ2),Q) ,ρ1(ζ2))$ expand(%);

print("k=2,l=2")$

A22: diff( h(ζ2,ρ2(ζ1),Q) ,ζ2)$ expand(%);

B22: diff( h(ζ2,ρ2(ζ2),Q) ,ζ2)$ expand(%);

C22: diff( h(ζ2,ρ2(ζ1),Q) ,ρ2(ζ1))$ expand(%);

D22: diff( h(ζ2,ρ2(ζ2),Q) ,ρ2(ζ2))$ expand(%);

e228k1l1: ( ρ1(ζ1)_ρ1(ζ2) ) / ( ζ1_ζ1_(ρ1(ζ1)-ρ1(ζ2))^2 )  \*  ( (A11_B11)/(C11*D11) ) ;

e228k1l2: ( ρ1(ζ1)_ρ2(ζ2) ) / ( ζ1_ζ2_(ρ1(ζ1)-ρ2(ζ2))^2 )  \*  ( (A12_B12)/(C12*D12) ) ;

e228k2l1: ( ρ2(ζ1)_ρ1(ζ2) ) / ( ζ2_ζ1_(ρ2(ζ1)-ρ1(ζ2))^2 )  \*  ( (A21_B21)/(C21*D21) ) ;

e228k2l2: ( ρ2(ζ1)_ρ2(ζ2) ) / ( ζ2_ζ2_(ρ2(ζ1)-ρ2(ζ2))^2 )  \*  ( (A22_B22)/(C22*D22) ) ;

e228: e228k1l1 + e228k1l2 + e228k2l1 + e228k2l2;

xthru(e228);
factor(num(%)) / factor(denom(%));

/***************************/

And so here is the clipboard copy of the backtrace;

> ASSERT INFO:
> wxMaxima.cpp(438): assert "cell != NULL" failed in DoConsoleAppend(): There was an error in generated XML!
> 
> Please report this as a bug.
> 
> BACKTRACE:
> [1] ~ConvertedBuffer /usr/include/wx-3.0/wx/string.h:3490
> [2] ~ConvertedBuffer /usr/include/wx-3.0/wx/string.h:3490
> [3] wxMaxima::ReadMath(wxString&) /home/sbh/SW/wxMaxima/git/wxmaxima-code/src/wxMaxima.cpp:1197
> [4] wxMaxima::ClientEvent(wxSocketEvent&) /home/sbh/SW/wxMaxima/git/wxmaxima-code/src/wxMaxima.cpp:717
> [5] wxAppConsoleBase::CallEventHandler(wxEvtHandler_, wxEventFunctor&, wxEvent&) const
> [6] wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler_, wxEvent&)
> [7] wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler_)
> [8] wxEvtHandler::TryHereOnly(wxEvent&)
> [9] wxEvtHandler::ProcessEventLocally(wxEvent&)
> [10] wxEvtHandler::ProcessEvent(wxEvent&)
> [11] wxEvtHandler::ProcessPendingEvents()
> [12] wxAppConsoleBase::ProcessPendingEvents()
> [13] wxApp::DoIdle()
> [14] g_main_context_dispatch
> [15] g_main_loop_run
> [16] gtk_main
> [17] wxGUIEventLoop::DoRun()
> [18] wxEventLoopBase::Run()
> [19] wxAppConsoleBase::MainLoop()
> [20] wxEntry(int&, wchar_t_*)
> [21] main /home/sbh/SW/wxMaxima/git/wxmaxima-code/src/main.cpp:114
> [22] __libc_start_main
> [23] _start

and after closing that dialog box I get;

> XML parsing error: 'mismatched tag' at line 1

I pulled anew from GIT today and rebuilt it to try and mitigate the possible issue, but it is still there. build_info() gives;

> build_info(version="branch_5_38_base_82_g07ec0e0",timestamp="2016-05-29 19:24:10",host="x86_64-unknown-linux-gnu",lisp_name="SBCL",lisp_version="1.3.2")

Please let me know if I need to add anything more.

**Comment by gunterkoenigsmann** [comment] 2016-09-30 20:14
I hope that I have fixed the issue in the nightly build.
...but I currently run into the following error message:

`
(%i45)	/***************************/
reset();
kill(all);

llinel:244$

ddepends(ρ1,[ζ1,ζ2]);
ddepends(ρ2,[ζ1,ζ2]);

h(zeta,rho,Q):=1-Qrho^2-zetarho*(1-rho^2);

print("A__ = h_{2,1}^{(1,0)}(ζk,ρ1^{(k)})")$
print("B = h_{2,1}^{(1,0)}(ζl,ρ2^{(l)})")$
print("C = h_{2,1}^{(0,1)}(ζk,ρ1^{k)})")$
print("D = h_{2,1}^{(0,1)}(ζ_l,ρ_2^{l)})")$

print("k=1,l=1")$

A11: diff( h(ζ1,ρ1(ζ1),Q) ,ζ1)$ expand(%);

B11: diff( h(ζ1,ρ1(ζ2),Q) ,ζ1)$ expand(%);

C11: diff( h(ζ1,ρ1(ζ1),Q) ,ρ1(ζ1))$ expand(%);

D11: diff( h(ζ1,ρ1(ζ2),Q) ,ρ1(ζ2))$ expand(%);

print("k=1,l=2")$

A12: diff( h(ζ1,ρ1(ζ1),Q) ,ζ1)$ expand(%);

B12: diff( h(ζ2,ρ2(ζ2),Q) ,ζ2)$ expand(%);

C12: diff( h(ζ1,ρ1(ζ1),Q) ,ρ1(ζ1))$ expand(%);

D12: diff( h(ζ2,ρ2(ζ2),Q) ,ρ2(ζ2))$ expand(%);

print("k=2,l=1")$

A21: diff( h(ζ2,ρ2(ζ1),Q) ,ζ2)$ expand(%);

B21: diff( h(ζ1,ρ1(ζ2),Q) ,ζ1)$ expand(%);

C21: diff( h(ζ2,ρ2(ζ1),Q) ,ρ2(ζ1))$ expand(%);

D21: diff( h(ζ1,ρ1(ζ2),Q) ,ρ1(ζ2))$ expand(%);

print("k=2,l=2")$

A22: diff( h(ζ2,ρ2(ζ1),Q) ,ζ2)$ expand(%);

B22: diff( h(ζ2,ρ2(ζ2),Q) ,ζ2)$ expand(%);

C22: diff( h(ζ2,ρ2(ζ1),Q) ,ρ2(ζ1))$ expand(%);

D22: diff( h(ζ2,ρ2(ζ2),Q) ,ρ2(ζ2))$ expand(%);

e228k1l1: ( ρ1(ζ1)ρ1(ζ2) ) / ( ζ1ζ1(ρ1(ζ1)-ρ1(ζ2))^2 ) * ( (A11B11)/(C11*D11) ) ;

e228k1l2: ( ρ1(ζ1)ρ2(ζ2) ) / ( ζ1ζ2(ρ1(ζ1)-ρ2(ζ2))^2 ) * ( (A12B12)/(C12*D12) ) ;

e228k2l1: ( ρ2(ζ1)ρ1(ζ2) ) / ( ζ2ζ1(ρ2(ζ1)-ρ1(ζ2))^2 ) * ( (A21B21)/(C21*D21) ) ;

e228k2l2: ( ρ2(ζ1)ρ2(ζ2) ) / ( ζ2ζ2(ρ2(ζ1)-ρ2(ζ2))^2 ) * ( (A22B22)/(C22*D22) ) ;

e228: e228k1l1 + e228k1l2 + e228k2l1 + e228k2l2;

xthru(e228);
factor(num(%)) / factor(denom(%));
(%o1)	[__,labels,tr-unique,lispdisp]
(%o0)	done
(%o2)	ddepends(ρ1,[ζ1,ζ2])
(%o3)	ddepends(ρ2,[ζ1,ζ2])
(%o4)	h(zeta,rho,Q):=1-Qrho^2+(-zetarho)*(1-rho^2)
"A__ = h_{2,1}^{(1,0)}(ζk,ρ1^{(k)})"" "
"B = h_{2,1}^{(1,0)}(ζl,ρ2^{(l)})"" "
"C = h_{2,1}^{(0,1)}(ζk,ρ1^{k)})"" "
"D = h_{2,1}^{(0,1)}(ζ_l,ρ_2^{l)})"" "
"k=1,l=1"" "
(%o11)	2*zetarho*ρ1(ζ1)*('diff(ρ1(ζ1),ζ1,1))
(%o13)	0
(%o15)	2*zetarho*ρ1(ζ1)
(%o17)	2*zetarho*ρ1(ζ2)
"k=1,l=2"" "
(%o20)	2*zetarho*ρ1(ζ1)*('diff(ρ1(ζ1),ζ1,1))
(%o22)	2*zetarho*ρ2(ζ2)*('diff(ρ2(ζ2),ζ2,1))
(%o24)	2*zetarho*ρ1(ζ1)
(%o26)	2*zetarho*ρ2(ζ2)
"k=2,l=1"" "
(%o29)	0
(%o31)	0
(%o33)	2*zetarho*ρ2(ζ1)
(%o35)	2*zetarho*ρ1(ζ2)
"k=2,l=2"" "
(%o38)	0
(%o40)	2*zetarho*ρ2(ζ2)*('diff(ρ2(ζ2),ζ2,1))
(%o42)	2*zetarho*ρ2(ζ1)
(%o44)	2*zetarho*ρ2(ζ2)
incorrect syntax: ρ1 is not an infix operator
228k1l1: ( ρ1(ζ1)ρ1(
                  ^
`

**Comment by brettsbh** [comment] 2016-09-30 20:27
I'm not super git-smart ;) but I'll try the nightly build tonight (if I can figure it out). I didn't touch Maxima but the build_info() got it right. I did "git pull/make distclean/config/make/make allmo/sudo make install" wxMaxima though. I did mangle linel() and depends() because I didn't want them working - hope that didn't cause trouble - I should have just left them out.

**Comment by gunterkoenigsmann** [comment] 2016-10-01 08:15
Ok... ...found out the first few things:
 - The problem isn't solved in the nightly build.
 - wxMaxima teaches maxima to talk in XML and
 - your example makes maxima send a 12-Megabytes-equation to wxMaxima that has more opening parenthesis than closing ones.

I am afraid that until we don't find a more minimal example it will be near to impossible where the actual error lies.

**Comment by gunterkoenigsmann** [comment] 2016-10-03 15:02
If I output e228 and then copy-and-paste it again into maxima I get the same error. In this case the cause is that between one closing parenthesis and the next opening one there is no multiplication dot - which makes the whole first parenthesis an function name. Don't know if this is a bug on maxima's side, though, or a bug in wxMaxima's copy-and-paste logic.

**Comment by gunterkoenigsmann** [comment] 2016-10-15 06:14
Seems like the copy-and-paste problem was an alltogether different bug that should be resolved by now. ...let's hope we'll find a smaller example that allows us to resolve the original problem.

**Comment by gunterkoenigsmann** [comment] 2018-01-27 15:45
Ok... ...the problem was simple: A comment start without comment end - and 2-3 bugs that were triggered by that.

**Closed by gunterkoenigsmann** 2018-01-27 15:45 UTC
Labels: bug, needs-investigation
