### ISSUE TITLE
file saves binom.wxmx but will not come back up

### ISSUE THREAD

**Issue by zmth** [andrejv/wxmaxima#1026] opened 2018-08-25 08:34 UTC
again and again it does this file saves ok and then will NOT come back up and i spend hours and hours then to have the file not load says xml parsing error. Then why did it save it ! Can you please fix this file. by giving me somewhere to email it.

**Comment by gunterkoenigsmann** [comment] 2018-08-25 08:49
Wow... ...such a thing didn't happen for a long time. Which wxMaxima version are you using? If it is a version from<2015 chances are high that the current nightly build of wxMaxima will automatically fix the issue. If not the process of repairing nearly every possible error is: 

 - Make a copy of the file, 
 - rename the copy to something ending in .zip, 
 - unzip it
 - open the content.xml with an XML-aware text editor
 - and hope that your text editor instantly informs you where the error lies.

The current nightly build of wxMaxima will be able to open the content.xml, after it has been fixed.

If that doesn't help you can still open the .wxmx file in an text editor. And my mail address is wxMaxima at peterpall . de.

If you are willing to send me the broken file I am grateful as with a bit of luck it will help me resolving the actual problem that caused the file to corrupt.

Unfortunately my computer currently isn't in working order so I will only be able to repair the file by hand in approximately a week.

**Comment by gunterkoenigsmann** [comment] 2018-08-25 09:03
What is the exact error message?  The things I have ever seen were:

 - an illegal character in the file. The current nightly build should fix that kind of error whilst opening the file.
 - a truncated file due to a broken hard disk. Normally the content.xml file can be recovered in this case using an text editor as it is at the beginning of the .wxmx file and isn't compressed.
 - a missing closing XML tag
 - and a completely garbled <output> tag. Which isn't a problem as if you delete <output> tags including the matching closing </output> using the text editor the content.xml cannot still be opened by the nightly build of wxMaxima.

**Comment by zmth** [comment] 2018-08-25 09:04
thanks for your reply:
wxMaxima version: 13.4.0
 Maxima version: 5.31.1
 Maxima build date: 2013-09-24 09:49:12
 Host type: i686-pc-mingw32
 Lisp implementation type: GNU Common Lisp (GCL)
 Lisp implementation version: GCL 2.6.8
 
before years ago same thing hapenned and they fixed it easily. I don't have an xml  editor don't even know what XML means. Don't have any way to send it to peterpall . de as is not a valid email address. i renamed it binom.zip and will try to upload here
[binom.zip](https://github.com/andrejv/wxmaxima/files/2320497/binom.zip)
thanks

**Comment by zmth** [comment] 2018-08-25 09:10
error says " wxMaxima encountered an error loading C:\maxima\binom.wxmx "
then i press ok and it replies " XML parsing error: 'not well-formed  (invalid token)' at line 828 "

I brought up the file in wordpad but unfortunately there is nothing in wordpad that can show line numbers

**Comment by zmth** [comment] 2018-08-25 09:26
supposed to be on line 828
<line></line>

**Comment by zmth** [comment] 2018-08-25 09:27
keeps changing line 828  to nonsense when i press comment above. Try again
<line> (small left arrow) <line>

**Comment by gunterkoenigsmann** [comment] 2018-08-25 10:30
As I have said I will have a working computer again in a week. I'll try to find a way to fix the file using my cellphone but I can't guarantee I find one.

But since you are still using the 2013 version of wxMaxima I am confident that a quick fix would be uninstalling wxMaxima and installing the version from https://wolfgang.dautermann.at/maxima/nightlybuild/ will resolve the problem: the current wxMaxima version will automatically fix all kinds of unopenable files I have ever seen from the 2013 version of wxMaxima.

Am 25. August 2018 11:04:23 MESZ schrieb zmth <notifications@github.com>:
>
>thanks for your reply:
>wxMaxima version: 13.4.0
> Maxima version: 5.31.1
> Maxima build date: 2013-09-24 09:49:12
> Host type: i686-pc-mingw32
> Lisp implementation type: GNU Common Lisp (GCL)
> Lisp implementation version: GCL 2.6.8
> 
>before years ago same thing hapenned and they fixed it easily. I don't
>have an xml  editor don't even know what XML means. Don't have any way
>to send it to peterpall . de as is not a valid email address. i renamed
>it binom.zip and will try to upload here
>[binom.zip](https://github.com/andrejv/wxmaxima/files/2320497/binom.zip)
>thanks
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/andrejv/wxmaxima/issues/1026#issuecomment-415954985

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by gunterkoenigsmann** [comment] 2018-08-25 10:37
You are correct: the character is an Escape sign and not allowed in XML so it will cause the error you have encountered.

New enough versions of wxMaxima will automatically repair this error when opening the file.

**Comment by zmth** [comment] 2018-08-26 12:04
So now have the .xml file and next if i 'fiddle' with this flle , deleting, changing things etc. then how do i get it back to a .wxmx file to try and load again ?
   On Saturday, August 25, 2018, 5:37:22 AM CDT, Gunter Königsman <notifications@github.com> wrote:  
 
 
You are correct: the character is an Escape sign and not allowed in XML so it will cause the error you have encountered.

New enough versions of wxMaxima will automatically repair this error when opening the file.

**Comment by gunterkoenigsmann** [comment] 2018-08-26 17:33
By default it installs itself into the directory c:/maxima_current

The rationale behind this is that this path doesn't contain a whitespace which the default install path in many countries does.

**Comment by gunterkoenigsmann** [comment] 2018-09-02 10:26
My computer works again => opened the file with a new wxMaxima and saved it again. It should be openable now again by any wxMaxima now that was released after 2011.
[binom.zip](https://github.com/andrejv/wxmaxima/files/2343207/binom.zip)

If you have still problems just comment on this thread and I will answer your messages.

**Closed by gunterkoenigsmann** 2018-09-02 10:26 UTC

**Comment by zmth** [comment] 2018-09-18 18:47
ok thanks
I did find on another computer did have a newer version 5.38.1 which did bring up the prior damaged file, with a notice, and corrected it also.
If in newer version of maxima 5.38.1 bring up a filed saved with older version maxima 5.28.0-2 get a warning notice and also if bring up
a file saved with newer 5.38.1 in the older version 5.28.0-2.

 Funny seems the older version more efficient because the file saved by the
newer version was around 87kb and after bringing it up in  older version 5.28.0-2 and saving it then it was only about 13kb.

**Comment by gunterkoenigsmann** [comment] 2018-09-21 05:28
There are 3 reasons:
 - Newer versions of wxMaxima include higher-resolution plots in the worksheet by default.
 - Newer versions of wxMaxima use antialiassing: If only a third of a pixel is hit by a line the pixel is only drawn light gray, not completely black or completely white. Which greatly improves the quality of the images, but also greatly increases the number of colors the image contains => we no more have to store 1..3 bit per pixel but 8...24 bit per pixel.

Additionally the text portion of the file is no more compressed:

The .wxmx file internally is a .zip archive, as is a .docx, a .odt or nearly every other file a modern program creates.

.zip files offer the feature of compressing turning of compression for their contents, which, as you have experienced, makes the file smaller, but comes with a number of drawbacks:

- if the text is compressed and the file is truncated somehow (disk or filesystem error or disk full or...) the information on how to uncompress the file is lost => reconstructing the contents of faulty compressed files is hard
 - many folks use a version control system like subversion or git that records all changes you ever have made to a file: As each individual change is small and the changes are recorded in a compressed form recording the change to uncompressed files doesn't use much memory (normally the memory used for all the changes you did in about 5 years is roughly as big as the actual file). But it provides you with an unlimited undo facility. Additionally if you store your git or subversion repository not on your local disk but on the other side of the world you'll have a complete backup of all the history of all of your files that will even survive a meteorite crash. If you try to do the same to a compressed file any change in the file is likely to change all of the compressed text => storing the history of compressed files tends to use up much memory.
 - and the amount of hard disk space saved often is small as the text rarely is bigger than a few kilobytes and therefore can only be reduced by a fraction of a few kilobytes.

=> Most of the increase of the file size is caused by an improved image quality. The rest (which should be small) helps with recovering broken files or saving the file's history.
