### ISSUE TITLE
Can not scroll to the correct position of a found text!

### ISSUE THREAD

**Issue by mleoking** [andrejv/wxmaxima#299] opened 2013-11-29 15:57 UTC
When you find a text in a long wxmx file. The editor can not correctly scroll to the position of a found text!

For example when you search "13." in the following window:

![screenshot_1](https://f.cloud.github.com/assets/5763751/1645973/6feb7aba-590e-11e3-829d-e8602aabaf82.png)

"13." is just within the current window. The editor should not scroll when the first "13." is found in the current window. However, the editor scroll down to the following window when I press Find Next button:

![screenshot_2](https://f.cloud.github.com/assets/5763751/1645980/b972f4e2-590e-11e3-966e-2568d6db0540.png)

There is no "13." in this window at all.

I want to provide the test wxmx file to reproduce the error. However, I did not find how to upload a file from the git hub website interface. 

wxMaxima version: 13.4.0
Maxima version: 5.31.2
Maxima build date: 2013-10-07 23:05:06
Host type: i686-pc-mingw32
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.8

**Comment by gunterkoenigsmann** [comment] 2015-04-27 19:40
Found the cause: ScrollToCell scrolls to the right editor cell. But if this cell is 20 lines long and the screen only 15 - scrolling to the right cell isn't enough.

**Comment by gunterkoenigsmann** [comment] 2015-05-15 16:16
Ok... seems scrolling to the right *cell* won't help with multi-line cells.

    ShowPoint(m_activeCell->PositionToPoint(parser));

should do the right thing instead.

**Comment by gunterkoenigsmann** [comment] 2015-05-15 16:23
Fixed with commit 614bec1b3321f88f7247969d2210d03ad4f9b03a.

**Closed by gunterkoenigsmann** 2015-05-15 16:23 UTC
Labels: bug
