### ISSUE TITLE
wxMaxima chokes on lisp objects

### ISSUE THREAD

**Issue by danielvolinski** [andrejv/wxmaxima#938] opened 2017-11-11 10:36 UTC
Using:
version=5.41.0, timestamp=2017-10-04 18:04:14, host=i686-w64-mingw32, lisp_name=SBCL,list_version=1.3.12

1. I open Wxmaxima
2. File->Open demo-dlsode.mac in directory $MAXIMA/share/maxima/5.41.0/share/odepack
3. I add as a first line: load(dlsode)$
4. Ctrl+R (Evaluate all visible cells)

I get an error in a "wxWidget Debug Alert" window. If I continue I get the correct results but also another error in a "Wxmaxima error" window.

**Comment by gunterkoenigsmann** [comment] 2017-11-12 19:15
I can reproduce this error on my computer. And wxMaxima is right in complaining: From maxima it gets

{{{
<mth>
  <lbl>(%o14) </lbl>
  <r>
   <t>[</t>
   <r>
    <t>[</t>
    <v>f</v>
    <t>,</t>#<FUNCTION (LAMBDA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $T
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $Y1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $Y2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            $Y3)) {10030FC77B}>
     <t>]</t>
     </r>
    <t>,</t>
    <r>
     <t>[</t>
     <v>vars</v>
     <t>,</t>
     <r>
      <t>[</t>
      <v>t</v>
      <t>,</t>
      <v>y1</v>
      <t>,</t>
      <v>y2</v>
      <t>,</t>
      <v>y3</v>
      <t>]</t>
      </r>
     <t>]</t>
     </r>
    <t>,</t>
    <r>
     <t>[</t>
     <v>mf</v>
     <t>,</t>
     <n>21</n>
     <t>]</t>
     </r>
    <t>,</t>
    <r>
     <t>[</t>
     <v>neq</v>
     <t>,</t>
     <n>3</n>
     <t>]</t>
     </r>
    <t>,</t>
    <r>
     <t>[</t>
     <v>lrw</v>
     <t>,</t>
     <n>58</n>
     <t>]</t>
     </r>
    <t>,</t>
    <r>
     <t>[</t>
     <v>liw</v>
     <t>,</t>
     <n>23</n>
     <t>]</t>
     </r>
    <t>,</t>
    <r>
     <t>[</t>
     <v>rwork</v>
     <t>,</t>
     <v>Lisp array [58]</v>
     <t>]</t>
     </r>
    <t>,</t>
    <r>
     <t>[</t>
     <v>iwork</v>
     <t>,</t>
     <v>Lisp array [23]</v>
     <t>]</t>
     </r>
    <t>,</t>
    <r>
     <t>[</t>
     <v>fjac</v>
     <t>,</t>#<FUNCTION (LAMBDA
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $T
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $Y1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $Y2
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             $Y3)) {10030FBFDB}>
      <t>]</t>
      </r>
     <t>]</t>
     </r>
    </mth>
}}}
...which indeed is no valid xml.

To me it looks like odepack inserts text that isn't XML-formatted into the XML stream wxMaxima's wxMathml.lisp creates. And like this text contains something that looks like a <FUNCTION> tag. Which doesn't exist. But I don't know enough lisp to be of real help here.

**Comment by gunterkoenigsmann** [comment] 2017-11-13 07:09
Forwarded this bug to the maxima developers as https://sourceforge.net/p/maxima/bugs/3353/ 
Kind regards,
Gunter.

**Comment by gunterkoenigsmann** [comment] 2017-11-17 06:51
Ok... ...the bug is closed as "Wontfix", which is OK: The actual problem seems to be that wxMaxima's wxmathml.lisp doesn't know how to identify that the lisp wants to give the ASCII representation of an unprintable lisp object (which is wrapped in "#<" and ">")... ...and therefore doesn't call wxxml-fix-string on it. The thing we now need a lisp wizard for is to find which code path needs the call to this function.

**Closed** 2017-11-19 09:05 UTC
Labels: bug
