### ISSUE TITLE
Lapack

### ISSUE THREAD

**Issue by wognath** [andrejv/wxmaxima#207] opened 2012-04-03 21:09 UTC
Lapack seems to work very well in xMaxima.  It would be very nice to have it available in wxMaxima as well.  However, when I type "load(lapack)", nothing happens except the message "Reading Maxima output" or "Maxima is calculating" for a very long time.  I have read that lapack takes some time, but it loads in ~2 seconds in xMaxima.  

It would be much appreciated if someone could look into this.  Thanks in advance, and thanks for wxMaxima:  I hardly ever use Mathematica any more!

**Comment by gunterkoenigsmann** [comment] 2015-02-14 21:10
The problem seems to be solved with the current git master. At least on my computer:

      wxMaxima version: 14.12.0
      Maxima version: branch_5_35_base_173_g0ec6c03
      Maxima build date: 2015-02-13 09:47:24
      Host type: x86_64-unknown-linux-gnu
      System type: BSD BSD NIL
      Lisp implementation type: GNU Common Lisp (GCL)
      Lisp implementation version: GCL 2.6.12

It was reproducible here a few months ago => closing this issue for now.

**Closed by gunterkoenigsmann** 2015-02-14 21:10 UTC
