### ISSUE TITLE
Unicode paths on Windows

### ISSUE THREAD

**Issue by XaoDefyMi2** [andrejv/wxmaxima#425] opened 2015-02-19 13:14 UTC
-5.35.1: wxMaxima enters in a loop error when opening wxm or wxmx files stored in a path with unicode characters. Ok with paths without unicode characters. Can open wxm or wxmx files asociated to wxMaxima from explorer.
-5.35.1.2: Same paths with unicode issue, but can't open wxm or wxmx files asociated to wxMaxima from explorer.
-None of this issues for:
wxMaxima version: 14.9.0
Maxima version: 5.34.1
Maxima build date: 2014-11-11 09:57:09
Host type: i686-pc-mingw32
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.11

**Comment by gunterkoenigsmann** [comment] 2015-02-28 18:08
Arrgh! If I understood it well the home dir is in a unicode character dir on windows with some locales. Will try to test the current nightly build next week hoping the problem is solved here.

**Comment by gunterkoenigsmann** [comment] 2015-07-02 18:06
Seems like wxWidgets trys to convert paths to ASCII before opening files. Sometimes it seems to fail to find the right characters for accessing the home dir on the current computer.

**Comment by gunterkoenigsmann** [comment] 2016-01-15 23:02
Should be fixed by now. At least if wxWidgets has an idea how to html-escape all unicode characters that are used in the current file and directory name.

**Closed by gunterkoenigsmann** 2016-01-15 23:02 UTC
Labels: bug
