### ISSUE TITLE
wxMaxima does not handle maxima crashes well

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#693] opened 2016-03-31 06:45 UTC
The following maxima function cause maxima to run out of memory:

    f(n):= if n<2 then 1 else f(n-1)+f(n-2)

Maxima compiled with clisp will crash for `f(500)`. When maxima crashes, wxMaxima crashes also. This should be handled better in wxmaxima.

**Comment by gunterkoenigsmann** [comment] 2016-03-31 07:11
On my system neither the crash of maxima seems not to be reproducible.
But I tend to use clisp only for things that can run out of ram and until now I haven't experienced a crash here => I am afraid that this time something in my system hinders me from helping with the debugging.

**Comment by andrejv** [comment] 2016-03-31 19:00
So this seems strange to reproduce. I only get a crash if I start wxmaxima from the terminal using

    open wxMaxima.app

If I start it from the Finder, there is no crash.

**Comment by gunterkoenigsmann** [comment] 2016-04-01 06:30
Committed some additional changes that should make sure that we don't attempt to read the stderr of a maxima process that no more exists hoping that this is the issue. If not I would search for the problem in MathParser: There still are cases in which invalid xml code does crash the parser. Additionally we silently ignore tags with too low a number of arguments (function tag without function name, etc. Don't know if we should pop up warnings (or somehow show them in the worksheet) here.

**Comment by andrejv** [comment] 2016-04-01 08:58
The bug is still present.

I should have mentioned I'm using wxWidgets from git, so maybe it is a bug there.

**Comment by gunterkoenigsmann** [comment] 2016-04-01 16:44
Will switch to the git version, too and try to reproduce the crash. Normally if I can reproduce a crash a stack backtrace made by gdb or apport normally (that is, if the error didn't overwrite the call stack) contains the information which line of which file the wxMaxima crashed in. And solving a problem of which the line number is known normally is easy.

**Comment by gunterkoenigsmann** [comment] 2016-04-01 16:57
With the git version of wxWidgets my linux computer still won't crash if clisp crashes. On windows (with a wxWidgets release, though) I can provoke crashes by flooding wxMaxima with an endless stream of xml data from maxima, though. ...does the xml monitor show something weird just before the crash? Sometimes linux seems to be forgiveful for many times of errors, though....

**Closed** 2016-04-02 08:29 UTC
Labels: bug
