### ISSUE TITLE
inconsistent tensor notation for the output

### ISSUE THREAD

**Issue by murakamiriyugi** [andrejv/wxmaxima#635] opened 2016-01-13 05:42 UTC
wxMaxima 14.12.1
Maxima 5.37.3
Ubuntu 14.04.3

The following two codes ought to have 
(mathematically) identical outputs yet as
exemplified below, they are inconsistent.

INPUT
ishow(contract(g([],[ν,α]) * p([α],[μ]) * g([μ,ν],[])))$
OUTPUT
p

INPUT
ishow(contract(g([],[μ,α])*p([α,μ],[])))$
OUTPUT
p[α]^α

The quantity g([],[]) is the itensor package metric.

Maxima (and perhaps wXmaxima) should
use the second notation as the first one
can be ambiguous and/or confusing.

**Comment by gunterkoenigsmann** [comment] 2016-01-13 05:57
Dear murakamiriyugi,

Weird: On my computer the first of the two code snippets did return an
error message - which might be caused by the tensor stuff having been
changed a lot lately and me running a git version of maxima.

Since it seems like something has changed on the maxima side: Would you
be so kind as to forward your report to the maxima-discuss mailing list
on maxima.souceforge.net? Normally they react quickly to tensor problems.

Thanks a lot,
and kind regards,

  Gunter.

**Comment by murakamiriyugi** [comment] 2016-01-14 02:24
Correct me if I'm wrong but the tensor packages
are the ones that are kept mostly untouched for
more than five years already. After the modification
by Viktor T. Toth (around 2005 - 2008), the development
on the tensor side stagnated. Now, perhaps due to
some fixes and modifications of some other parts
of maxima (and/or wXmaxima), the tensor part
starts exhibiting some problems (eg., sometimes, ishow()
fails to output long (but not impossibly long) expressions,
causing the system to hang until you interrupt).

In any case, I have sent an email to the maxima mailing
list. Now that you mentioned it, it appears more of a 
Maxima problem rather than that of wXmaxima.
Thank you very much.

**Comment by gunterkoenigsmann** [comment] 2016-01-14 06:29
On 14.01.2016 03:24, murakamiriyugi wrote:
> Correct me if I'm wrong but the tensor packages
> are the ones that are kept mostly untouched for
> more than five years already. After the modification
> by Viktor T. Toth (around 2005 - 2008), the development
> on the tensor side stagnated. 
I won't correct you here as I assume that the tensor packages might have
been created with a specific task in mind and not being used by any
developer recently.
In the last weeks Victor did answer to requests on the mailing list
several times, though, telling that he changed something which means
that if there is need he still might be around.

> In any case, I have sent an email to the maxima mailing
> list. Now that you mentioned it, it appears more of a
> Maxima problem rather than that of wXmaxima.

You're welcome!

Let's hope that they answer that your problem can be solved as fast as
the last few were.

Kind regards,

  Gunter.

**Comment by gunterkoenigsmann** [comment] 2016-01-14 06:31
Will close this ticket to wxMaxima in the meantime. But feel free to re-open it if fixing the problem requires some work in wxMaxima, too.
Kind regards,
  Gunter.

**Closed by gunterkoenigsmann** 2016-01-14 06:31 UTC
