### ISSUE TITLE
Sidebar headings look weird when compiled against wxWidgets 3.1.0

### ISSUE THREAD

**Issue by badshah400** [andrejv/wxmaxima#783] opened 2016-10-15 00:12 UTC
The heading for various sidebar toolbars look weird with barely readable black on black text when wxmaxima is built against wxWidgets 3.1.0. Screenshot shows the Symbol, Greek symbols and History sidebars, but this is true for all the toolbars. No issue is seen when wxWidgets 3.0.x is used to build wxmaxima.

![screenshot from 2016-10-15 02-09-54](https://cloud.githubusercontent.com/assets/3532467/19405841/90f674f8-927c-11e6-94c9-d0400fb0a511.png)

**Comment by gunterkoenigsmann** [comment] 2016-10-15 04:27
I can acknowledge that. And this (and the fact that the header of non-docked sidebards looks weird, too) has hindered me from making the "find and replace" dialogue dockable.

...but AFAIK we cannot help this on the wxMaxima side. If you were willing to report it to the wxWidgets project that would be fine. Perhaps they will find a way to fix it. My guess is that they will have a hard time doing so, though: If the operating system doesn't offer dockable dialogues they have to mimick them by drawing them by hand and therefore have to duplicate the logic that creates the look-and-feel for all of the other dialogues.

**Comment by gunterkoenigsmann** [comment] 2016-12-11 08:18
In the wxWidgets wiki they say that the wxAUI module that draws the sidebars is still being actively developed. Let's hope that they find a way to fix this issue. Will close the issue for wxMaxima - not because I think that it isn't an issue but because it has to be fixed in an external library.

**Closed by gunterkoenigsmann** 2016-12-11 08:18 UTC
Labels: known issue

**Comment by gunterkoenigsmann** [comment] 2016-12-11 08:26
Finally found the according bug report for wxWidgets: I *knew* there must already be one so I didn't want to write one myself: http://trac.wxwidgets.org/ticket/4391

**Comment by gunterkoenigsmann** [comment] 2016-12-11 13:57
I was no more sure that this is actually the same bug as in the trac ticket so I've created a new one: http://trac.wxwidgets.org/ticket/17747

**Comment by badshah400** [comment] 2016-12-11 14:38
@gunterkoenigsmann Thanks a lot for following up on this issue, and taking it upstream.

**Comment by gunterkoenigsmann** [comment] 2016-12-11 16:24
I hope I was right in closing the issue again in the wxWidgets tracker: On my system it wasn't possible to reproduce it any more as soon as I switched to the git master of wxWidgets. But you never know if this applies to all possible systems and color schemes...
