### ISSUE TITLE
Split long lines up

### ISSUE THREAD

**Issue by andrejv** [andrejv/wxmaxima#171] opened 2011-04-20 07:53 UTC
Converted from [SourceForge issue 3101516](http://sourceforge.net/support/tracker.php?aid=3101516), submitted by antonvoropaev

It would be handy, if long lines were
split up according to window width
(like in XMaxima or in Maple).

**Comment by gunterkoenigsmann** [comment] 2015-02-07 07:49
Duplicate of Issue #286 => Closing it.

**Closed by gunterkoenigsmann** 2015-02-07 07:49 UTC
Labels: feature request, sf-tracker
