### ISSUE TITLE
wxplot2d with option [xy_scale] gives strange output

### ISSUE THREAD

**Issue by mirekslouf** [andrejv/wxmaxima#820] opened 2016-12-04 10:45 UTC
Sample input: wxplot2d(x+sin(x),[x,-5,5], [xy_scale, 0.5,1])$

Output is strange in two aspects:
1. the scale of the graph is NOT 0.5\*x and 1\*y
2. the size of the cell containing the graph is too large (as if [xy_scale, 1,1] was used)

See the attached files (WXMX with TXT extension and WXMX printed to PDF):
- WXMX.TXT: 
[test_wxplot2d_xy_scale.wxmx.txt](https://github.com/andrejv/wxmaxima/files/629406/test_wxplot2d_xy_scale.wxmx.txt)
- WXMX.PDF: 
[test_wxplot2d_xy_scale.wxmx.pdf](https://github.com/andrejv/wxmaxima/files/629407/test_wxplot2d_xy_scale.wxmx.pdf)

Version of my programs:

wxMaxima version: 16.4.2Maxima version: 5.38.1
Maxima build date: 2016-06-12 17:13:34
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.3.4

Windows 7 64-bit, PDFCreator 2.4, wxMaxima nightly build 2016-11-30

**Comment by gunterkoenigsmann** [comment] 2016-12-09 16:31
That indeed looks strange, even if I am no plot expert and might be wrong. I also can acknowledge that I am able to reproduce this bug. What I can tell is that it also happens with:

       plot2d(x+sin(x),[x,-5,5], [xy_scale, 0.5,1])$ 

In this command wxMaxima isn't involved =>I would beg you to report this bug to maxima (https://maxima.sourceforge.net) and will close it for wxMaxima, not because I think it is invalid, but because it is better handled in maxima.

Thanks a lot!
and kind regards,

   Gunter.

**Closed by gunterkoenigsmann** 2016-12-09 16:31 UTC

**Comment by mirekslouf** [comment] 2016-12-10 09:49
Thank you for the answer.
The issue was reported in Maxima (bug number: 3260) as suggested above.
