### ISSUE TITLE
wxdraw2d(polar(...)) fails after load(vect)

### ISSUE THREAD

**Issue by jabowery** [andrejv/wxmaxima#562] opened 2015-09-12 15:38 UTC
See attached screenshot.
![screen shot 2015-09-12 at 10 25 24 am](https://cloud.githubusercontent.com/assets/57646/9832237/4ee36228-593a-11e5-8af2-7a28df1fea31.png)

**Comment by andrejv** [comment] 2015-09-15 07:13
The problem is that the `vect` package defines `polar` as a constant. The usual solution is to quote the polar function:

    draw2d('polar(...));

but this is not currently supported by the `draw` package. I have informed the author of `draw` and this issue has been fixed in maxima git (that is the quoting works) so I'm closing this bugreport.

As a temporary workaround you can execute `kill(polar)` after loading `vect`. I don't know how this is going to affect the `vect` package though.

**Closed by andrejv** 2015-09-15 07:13 UTC
