### ISSUE TITLE
Cut / Copy via keyboard (Ctrl+C / Ctrl+X) does not work for text selected with the mouse

### ISSUE THREAD

**Issue by MSoegtropIMC** [andrejv/wxmaxima#1010] opened 2018-06-22 14:54 UTC
Dear wxMaxima Team,

when I select text from an input field (not an output field) via dragging over it with the left mouse button pressed, Ctrl+C and Ctrl+X don't work. Copy/cut works fine for text selected with a double click (single words) and for test selected with shift+cursor keys. Also dragging over selection does work if the respective command was focused before (click in it and do a cursor key movement and then drag select works).

Also it seems like the Edit / Copy / Cut menu always works, just Ctrl+C, Ctrl+X doesn't.

This is 100% reproducible for me. I would also say that this did work in previous versions. If this is of interest, I could check which versions did still work.

Best regards,

Michael

-------------------------------------------------------------
wxMaxima version: 17.10.1
Maxima version: 5.41.0a_dirty
Maxima build date: 2017-10-24 09:10:17
Host type: x86_64-w64-mingw32
System type: Win32 10.0.14393 X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.3.18
-------------------------------------------------------------

**Comment by gunterkoenigsmann** [comment] 2018-06-23 07:51
This problem should be fixed in the nightly build and in the 2018 release. I never encountered it myself as it depends on the way the text has been selected. Which is unfortunate as others trigger it reliably.

**Comment by MSoegtropIMC** [comment] 2018-06-25 08:29
@gunterkoenigsmann : Hmm I thought I have the latest version, but apparently there is an 18.X version of wxMaxmia, just I can't find a pre-built Windows installer for it. Would I have to build it from sources to test it, or am I just unable to find the right download location?

**Comment by gunterkoenigsmann** [comment] 2018-06-25 08:55
I would need help on testing https://wolfgang.dautermann.at/maxima/nightlybuild/ but the official release should be at maxima.sourceforge.net.

**Comment by gunterkoenigsmann** [comment] 2018-06-29 15:34
Seems like the 2018 release has never taken place...

---

Yes, please open a separate issue: It is way easier to track things if each has its own issue.

Is the offset in selecting things dependent on the font being used? I cannot reproduce it here.

**Closed by gunterkoenigsmann** 2018-06-29 15:34 UTC

**Comment by MSoegtropIMC** [comment] 2018-06-29 16:28
I created bug #1012 for the click offset issue - including a sample and style file for (hopefully) easy reproduction.
