### ISSUE TITLE
coma external plot file

### ISSUE THREAD

**Issue by danielvolinski** [andrejv/wxmaxima#729] opened 2016-06-04 19:29 UTC
I'm using the coma package.
The following commands create an external png file:

load(coma)$
F(s):=((s+3)*(s+4))/((s+2)*(s+1));
poles_and_zeros(F(s),xrange=[-5,0],yrange=[-2,2],
                file_name="12ClosedLoop2",terminal='png)$
show_image("12ClosedLoop2.png")$

However the following command does not create an external png file

root_locus(1/(1+k*F(s)),xrange=[-5,0],yrange=[-2,2],
           file_name="12ClosedLoop3",terminal='png)$
show_image("12ClosedLoop3.png")$

Why the difference? Is there another way to create an external png file?
Daniel Volinski

wxMaxima version: 
Maxima version: 5.38.0_dirty
Maxima build date: 2016-04-03 10:09:05
Host type: i686-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on maxima [192.168.43.2])

**Comment by gunterkoenigsmann** [comment] 2016-06-05 05:39
I have no experience with the coma package nor did I know that it
actually exists.

What I get from your first example is:

allroots: expected a polynomial; found %i*(s+3.0)(s+4.0)

Defining s as

F:rat((s+3)/(s+4))/((s+2)/(s+1))

and therefore formally declaring it to be a polynomial seems not to
change anything.

If the question is if there generally is a way to create external .png
files the following might work for you:

      load("draw");
      pngdraw(name,[contents]):=
      (
          draw(
              append(
                  [
                      terminal=pngcairo,
                      dimensions=wxplot_size,
                      file_name=name
                  ],
                  contents
              )
          ),
          show_image(printf(false,"~a.png",name))
      );
      pngdraw2d(name,[contents]):=
          pngdraw(name,gr2d(contents));

      pngdraw2d("Test",
              explicit(sin(x),x,1,10)
      );

I seem to remember that I have recently corrected a bug in show_image.
So you might want to update a nightly build of maxima if the .png files
are generated but not shown.

For coma-specific questions I am afraid I won't be able to help you too
much. But feel free to ask the maxima-discuss mailing list about it.

Kind regards,

     Gunter.

**Comment by danielvolinski** [comment] 2016-06-05 08:40
Hi Gunter,

Thank you for your observations.

In order to run my examples you will have to put multiplication symbols between (s+3) and (s+4) and also between (s+2) and (s+1) in the definition of F(s); for some reason the bug report system deletes both symbols.

In the first example (poles_and_zeros) an external png file is created, in the second example (root_locus) the png external file is not created.

I tried to use you suggestions in the following way:

pngdraw2d("12ClosedLoop3",root_locus(1/(1+k*F(s)),xrange=[-5,0],yrange=[-2,2]))$

But I got:

part: argument must be a non-atomic expression; found ""
#0: pngdraw(name=12ClosedLoop3,contents=[gr2d([""])])
#1: pngdraw2d(name=12ClosedLoop3,contents=[""])

How should I use your pngdraw2d with the root_locus command?

Thanks,

Daniel

**Comment by gunterkoenigsmann** [comment] 2016-06-05 09:11
The root_locus command seems not to output the data you have to pass to wxdraw2d but automatically calls wxdraw2d instead. There seems nothing we can do against this other than changing its source.

The problem is that wxdraw2d does to nearly the thing my command is doing:
 - It generates a scene for draw2d()
 - it passes the scene to this command appending the instruction to plot into an png file, sets the filename to the name of a temporary file and tells wxMaxima to delete this file after loading so the temporary file isn't lying around any longer.

...sounds fine, that: If the user wants to draw something on the screen wxdraw2d() is the right candidate. If the user wants to write the scene to a file this has to be done by draw2d() instead.

     wxdraw2d(terminal=pngcairo,file_name="test2",explicit(sin(x),x,0,1));

won't write to the file you instruct it to, either. Only in your case it is not up to the user to choose the drawing command....

Found a workaround:
Adding the following line after the

      load("coma");

tricks coma into believing that you aren't using wxMaxima - which means that it cannot use wxdraw2d() and will fallback to draw2d() that outputs the plots into a file instead if instructed to do so:

     plot_defaults:delete(wx=true,plot_defaults);

Will add a feature request to this bug tracker that wxdraw should allow setting the file name and keep the file if the user specified a name for it: I don't feel confident that I know enough lisp to do so myself but it should have avoided the problem.

Kind regards,

   Gunter.

**Comment by gunterkoenigsmann** [comment] 2016-06-05 09:18
Closing this ticked as duplicate of #730 hoping that my workaround works. It it doesn't feel free to repoen it.

**Closed by gunterkoenigsmann** 2016-06-05 09:18 UTC

**Comment by danielvolinski** [comment] 2016-06-05 15:29
Hi Gunter,

It works, thanks,

Daniel
