### ISSUE TITLE
underscored label cause problem

### ISSUE THREAD

**Issue by danielvolinski** [andrejv/wxmaxima#756] opened 2016-08-18 15:02 UTC
When using a variable name as line_element the export to Latex has problems
[514-13w.zip](https://github.com/andrejv/wxmaxima/files/425192/514-13w.zip)
If I use lineelement as the name, the process of creating the PDF file.
If I use line_element as the name, the process of creating the PDF file fails with:
! Missing \endcsname inserted.
<to be read again> 
                   \protect 
l.23 ...element}{{{line\_ element}}{1}{}{AMS.2}{}}
Notice that the failure is in the label line_element not in the usage of the variable name.

Also (%i11) is cut, not all the line is there.

**Comment by danielvolinski** [comment] 2016-08-18 15:16
I meant to say:
If I use lineelement as the name, the process of creating the PDF file is OK.
If I use line_element as the name, the process of creating the PDF file fails.

**Comment by gunterkoenigsmann** [comment] 2016-09-04 08:22
I cannot reproduce this on my system. Since my system is running a nightly build of wxMaxima I assume this problem has been fixed in the meantime. But one does never know...

**Comment by danielvolinski** [comment] 2016-09-04 16:20
Ok, I'll wait for the next release

**Comment by gunterkoenigsmann** [comment] 2016-09-05 05:17
Then I will close the bug since I am convinced to have resolved it - and beg you to reopen it if I am wrong.

**Closed by gunterkoenigsmann** 2016-09-05 05:17 UTC
