### ISSUE TITLE
missing input

### ISSUE THREAD

**Issue by charles843** [andrejv/wxmaxima#577] opened 2015-09-27 09:00 UTC
wxMaxima version: 13.4.0
Maxima version: 5.32.1
Maxima build date: 2014-01-10 01:52:55
Host type: x86_64-unknown-linux-gnu
Lisp implementation type: GNU Common Lisp (GCL)
Lisp implementation version: GCL 2.6.10

distro: linuxmint
install wxMaxima via software manager.

Hello! I have encountered a problem that input charactors are missing. For example, when I typed
    "abcdefgabcdefgabcdefgabcdefgabcdefg"
in an input cell, I got on my screen the following
    "bcdefacdefgabdfabcdefg"
What is strange is that when I typed the same thing again, what I got different staff on the screen!
Besides on my computer, I have tested this on a laptop and input characters are still missing now and then but the missing characters differ each time.

There are similar problems in text cells, too.

**Comment by gunterkoenigsmann** [comment] 2015-09-27 15:53
Does the same still happen if you use the wxmaxima version from 
https://launchpad.net/~peterpall/+archive/ubuntu/wxmaxima-nightlies/+packages
?

I assume this bug to reside on maxima's side, not to be caused by 
wxMaxima. But we have changed so much since 2013 that there might have 
been a bug here that is no more there.

Thanks a lot,
and

Kind regards,

   Gunter.

**Comment by gunterkoenigsmann** [comment] 2016-03-11 22:30
Is definitively resolved in the current version.

**Closed by gunterkoenigsmann** 2016-03-11 22:30 UTC
