### ISSUE TITLE
Issue with the newly released maxima-clisp-5.37.3.exe released 2015-11-14

### ISSUE THREAD

**Issue by ReneSci** [andrejv/wxmaxima#616] opened 2015-11-15 21:46 UTC
A (bug): In my worksheet I have have the definition below
TimeDateNumber(YY, MM, DD, hh, mm, ss) := block([MonthsOfYear, DaysOfMonth, HoursOfDays, MinsOfHour,
SecOfYear, SecOfMonth, SecOfDay, SecOfHour, timeNumber],
MonthsOfYear : 12,
DaysOfMonth : 32,
HoursOfDays : 24,
MinsOfHour : 60,
SecOfMin : 60,
SecOfHour : MinsOfHourSecOfMin,
SecOfDay : HoursOfDaysSecOfHour,
SecOfMonth : DaysOfMonthSecOfDay,
SecOfYear : MonthsOfYearSecOfMonth,
timeNumber : (YY-2000)SecOfYear + MMSecOfMonth + DDSecOfDay + hhSecOfHour + mm*SecOfMin + ss,
timeNumber);

As soon as I evaluate this input (I know that something like this has been included in maxima by now) - wxmaxima goes crazy - it makes an almost infinite big - emty - output cell, and the coursor disapprears. I tried to download todays overnight complilation, but it behaves in the same way. Tried to copy just the above test via an text editor (notepad++) and from there to an empty worksheet - same behaviour.
By the way build info says: 15.8.0 but "about" says 15.8.1 GIT - which version is it ?
best regards
Rene'

**Comment by daute** [comment] 2015-11-18 16:26
Hi,
As I announced on the Maxima mailinglist (https://sourceforge.net/p/maxima/mailman/message/34620046/) the installer is based on the latest git state of branch_5.37 from Maxima (the released source tarball was missing some commits) and the - at that time - latest version of the master branch of WxMaxima (the latest included commit was b6ad7372a2447689076d6325471e9c35a3c2e1cc ("Another LaTeX export issue.")).

I dont know, why it reports as 15.08.1 GIT - it is clearly AFTER release 15.08.2.

And I could not reproduce your problem here - the code contains syntax errors (e.g. (YY-2000)SecOfYear should be (YY-2000)*SecOfYear, ....), but when they are corrected your function is defined and I get the defined function in an output cell as expected.
 
Best regards, Wolfgang

**Comment by gunterkoenigsmann** [comment] 2015-11-18 20:01
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Have not been able to reproduce the bug, neither. The last time this
happened it was a font-related bug. Could you try if the instructions
found in
https://github.com/andrejv/wxmaxima/issues/486#issuecomment-132890605
resolve the issue?

Kind regards,

   Gunter.
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQJ8BAEBCgBmBQJWTNaWXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOjEgP/1NmdgKkVbx1fcW6BJZ25uMR
te2MHtvMpbVTeYUqiRmLHBgsi+7Sdd6uIBAdO+nnb5CW1NxCQADIb5jT7UASijVs
ty5HJk+9M3bG08B22P09s96ki4UxrHtBfXclL3E6GYdZwYUt7o+7JiL4DZxtVeFz
eKoWjEP8OqH3vyA6KHVHquvaZyyI4q1cTIsmckvh2DnOojpTBluvQMvwz+QIvx8M
odbDQlgrHtEm/5HnDWWT9mSevLWJo+uRGqDKm4HebhX9oEkboXct/TiY7jeNC/vJ
Woh89tI8VSbkgkbawTI4UiWx9sw5ythD+QH3HtLuDnB1f0gc34v3uyZPC9zRfUVM
j+E9TYMLrmenh61Yfi57KrOSkdnUEQCjo15TWasll2xotk1x0nteE0n/a3oZSpqk
m64c621+3fMs57SZr8u/+w3EdwzdPDc9kxqccG9XbmKHaRP2QvaLOQJYV2WPjBwf
GNCk9EOi8tzcgoP7Q9zOnI8+vPM/7eHfRje+KUbiPYqoES93YgzWPx7iIpfNWVU0
+kVil18pZ5pvHMKVuOqxzVVFbpZZq5z/qNJDTMW8U6yhsnjBx5FwM3t3ywij3q8D
39vMPjwwXUcOa7BEkq5S+Lmp7X6Mo8sRA1A/EPElTeVu/8XUndNuUR6TAOP6s7wm
GHsL3fgwhictJxiqvs/v
=vn7M
-----END PGP SIGNATURE-----

**Comment by ReneSci** [comment] 2015-11-18 20:08
Will try it asap

2015-11-18 21:01 GMT+01:00 Gunter Königsman <notifications@github.com>:

**Comment by ReneSci** [comment] 2015-11-23 10:40
I am sorry - there was an error while I did a copy/paste - all the * dissapears some how in my first post here.

Yesterday I downloaded the nightly build (wxMaxima version 15.10 unofficial) below are my observations: 

1) The above function now works again.

------------------------------------------

2) when I in a plot using wxdraw2d want to use an Greek lambda:

When I use [ESC] l [ESC] to enter an lambda into e.g. a key text I get

Maxima encountered a Lisp error:
PRINC: Character #\u03BB cannot be represented in the character set CHARSET:CP1252
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.

------------------------------------------

3)  {/symbol l} works - but only for draw2d - NOT wxdraw2d

-----------------------------------------

4)) Doing a re-plot I get this error:

Maxima encountered a Lisp error:
OPEN: #<OUTPUT BUFFERED FILE-STREAM CHARACTER
  #P"C:\\Users\\Rene\\maxout_5800.gnuplot"> already points to file "C:\\Users\\Rene\\maxout_5800.gnuplot", opening the file again for :OUTPUT may produce unexpected results
Automatically continuing.
To enable the Lisp debugger set *debugger-hook* to nil.



----------------------------------------------------------------------


5) Font: Error:

Message from maxima's stderr stream: 
(wgnuplot.exe:6592): Pango-WARNING **: couldn't load font "Times Not-Rotated 240", falling back to "Sans Not-Rotated 240", expect ugly output.

(wgnuplot.exe:6592): Pango-WARNING **: couldn't load font "symbol 240", falling back to "Sans 240", expect ugly output.

(wgnuplot.exe:6592): Pango-WARNING **: couldn't load font "Times 240", falling back to "Sans 240", expect ugly output.


I am using this set-up (and have been during for the past year)
-------------------------------------------------------------------------
set_draw_defaults(
user_preamble  = ["set xtics out", "set mxtics 10", "set ytics out", "set font 'Areal, 8'", "set zero 10^-100",  "set format y '%0.3se%03S'", "unset clip", "set autoscale y",  "set autoscale x" ],
xtics = true,
xtics_rotate = true,
xtics = DataFileTimeTics5th,
 font           = "Times",
  font_size      = 12,
   title          = PlotTitle,
        xlabel         = "Time",
ylabel         = PlotYlabel,
 grid           = true,
   palette        = gray,
        point_type    = 0,
point_size    = 1,
points_joined = true)$

----------------------------

6) Somehow, maxima-clisp-5.37.3.exe installs maxim in the root directory
c:/maxima-clisp-5.37.3 - and not in "Program Files" - I know it might not be a wxMaxima issue.


Best regards
Rene'

**Comment by daute** [comment] 2015-11-23 18:11
Hi,
concerning the installation path: Yes - and I did this on purpose when I created the installer for two reasons:

First the blank (between 'Program' and 'Files') can cause troubles.

And the second reason: When one builds maxima, you set the Installation path with "./configure --prefix=...". And the problem is, that the default installation path is then "c:\Program Files", if you install it on a 32bit Windows but "C:\Program Files (x86)" if you install it on a 64bit Windows. 
Since I can not be sure, that the path is not used (I did remove some hardcoded dependencies already), I decided that a **much better solution** is a fixed installation path (without blanks in the path). 
That just avoids a lot of problems when creating the crosscompiling-scripts for the Windows installer.

Best regards, Wolfgang

**Comment by gunterkoenigsmann** [comment] 2015-11-23 19:16
For the greek symbols in gnuplot: Can reproduce this on ubuntu => I assume this to be a gnuplot bug. Feel free to report your finding to the gnuplot project: Their ChangeLog does not seem to mention this to be a voluntary change.

Kind regards,

    Gunter.

**Comment by gunterkoenigsmann** [comment] 2015-11-24 06:00
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512



On 23.11.2015 11:40, Rene Hansen wrote:
> I am sorry - there was an error while I did a copy/paste - all the
> * dissapears some how in my first post here.
> 
> Yesterday I downloaded the nightly build (wxMaxima version 15.10 
> unofficial) below are my observations:
> 
> 1) The above function now works again.
> 
This is good news!
> ----------------------------------------------------------------------
- --
>
>  2) when I in a plot using wxdraw2d want to use an Greek lambda:
> 
> When I use [ESC] l [ESC] to enter an lambda into e.g. a key text I
> get
> 
> Maxima encountered a Lisp error: PRINC: Character #\u03BB cannot be
> represented in the character set CHARSET:CP1252 Automatically
> continuing. To enable the Lisp debugger set /debugger-hook/ to
> nil.
> 
Did hunt over a year for this bug. Unfortunately it cannot be fixed on
the wxMaxima, but only on the maxima side. The good news is that it
will be fixed in the next major release of maxima - and that the SBCL
installer - if somebody compiles one, that is - already will work.
> ----------------------------------------------------------------------
- --
>
>  3) {/symbol l} works - but only for draw2d - NOT wxdraw2d
> 
<ESC>l<ESC> might even on CCL, in this case. Looks like an gnuplot
issue to me - but I am not sure if it is the gnuplot build that was
included with the maxima installer or if this in the gnuplot source.

I suspect the latter - but will put Wolfgang on CC for this mail:
Perhaps he knows more about that.
> ----------------------------------------------------------------------
- --
>
>  4)) Doing a re-plot I get this error:
> 
> Maxima encountered a Lisp error: OPEN: #
> #P"C:\\Users\\Rene\\maxout_5800.gnuplot"> already points to file 
> "C:\Users\Rene\maxout_5800.gnuplot", opening the file again for
> :OUTPUT may produce unexpected results Automatically continuing. To
> enable the Lisp debugger set /debugger-hook/ to nil.
> 
Does this happen in Maxima (without wx), too? Looks like a maxima bug
to me.
> ----------------------------------------------------------------------
- --
>
>  5) Font: Error:
> 
> Message from maxima's stderr stream: (wgnuplot.exe:6592):
> Pango-WARNING **: couldn't load font "Times Not-Rotated 240",
> falling back to "Sans Not-Rotated 240", expect ugly output.
> 
> (wgnuplot.exe:6592): Pango-WARNING **: couldn't load font "symbol
> 240", falling back to "Sans 240", expect ugly output.
> 
> (wgnuplot.exe:6592): Pango-WARNING **: couldn't load font "Times
> 240", falling back to "Sans 240", expect ugly output.
> 
> 
> I am using this set-up (and have been during for the past year)
> 
> set_draw_defaults( user_preamble = ["set xtics out", "set mxtics
> 10", "set ytics out", "set font 'Areal, 8'", "set zero 10^-100",
> "set format y '%0.3se%03S'", "unset clip", "set autoscale y", "set
> autoscale x" ], xtics = true, xtics_rotate = true, xtics =
> DataFileTimeTics5th, font = "Times", font_size = 12, title =
> PlotTitle, xlabel = "Time", ylabel = PlotYlabel, grid = true, 
> palette = gray, point_type = 0, point_size = 1, points_joined =
> true)$
> 

This definitively is a gnuplot or a gnuplot packaging issue.

> ----------------------------------------------------------------------
- --
>
>  6) Somehow, maxima-clisp-5.37.3.exe installs maxim in the root
> directory c:/maxima-clisp-5.37.3 - and not in "Program Files" - I
> know it might not be a wxMaxima issue.
> 
This was intended: "Program Files" contains a space - and putting a
program into a bug with spaces always comes with the risk of
encountering strange bugs. In case that the other installers trigger
them the clisp installer still works.

Kind regards,

     Gunter.


-----BEGIN PGP SIGNATURE-----
Version: GnuPG v2

iQJ8BAEBCgBmBQJWUvqUXxSAAAAAAC4AKGlzc3Vlci1mcHJAbm90YXRpb25zLm9w
ZW5wZ3AuZmlmdGhob3JzZW1hbi5uZXQ1M0YwNDdDRTY2QjkxQjBGNzI0QzU0NUQ1
Qzg2QzBFNDIxMUQ1QjhFAAoJEFyGwOQhHVuOWEwP/ibiRw32ruhyGscK1xhCWFlz
GPwO7FBsiQORzgT+MeDlzSdaH14UNFXFx5lKv6ANSL8LcFvKPnAfoU7OGkccy+l/
zYWsgU3v7P5U2/zsXkEocBUn1QcpVvcV+QGx3PJoVSJMIMh+EF/DOCtnI8bTIGOm
wxECxFTmA200x8NVh3CPF0O9JQUmFIwtAVhygGRf+5RFzFcwZzM+71L06cTZ+AKs
RWqTmatiphWfF5lkJqDub+hRZbHKYRHcDroDr+JdNAaqtRXw7/PsCx8t8Qpx/iAS
pNSSPNW5DADUldNl9FcUQvAy9g6ShcGySevPvyxqtLPkqozY1uIkLeYvVktvB9I4
GymA3LWFWpXvekc82v6gc9tn73ITMlYLFwW20Iy7bzETV2LvBlXVNCnyUo2vgoje
38xfoEDH+NqG9vIVODbqXviV9QPpZt4RJ6xZfASXZSD9376Cdx4+oW/vhMKWFGY8
khoFbVYbM9fXrqNJzWUVNt8in7Jreq/wYthTldARATqOGTOybfHLml0aVFiyD6y8
Z50LfMamZtuzryCbRTMZGfQ3ffuME1qo8MR451jf+E1XnQgWwMg+iZIvnOS5feAr
aU77exTIBsvDnqm6282Yrtv/sbZ04jX6B9u1rU6WVUr8gfxbhFGeXu1nvRcGXjdu
3pIKwJMdqDgpB8jLWWVu
=zjyF
-----END PGP SIGNATURE-----

**Comment by ReneSci** [comment] 2015-12-01 21:32
Regarding the {/symbol l} versus [ESC] l [ESC] to get an lambda on a plot:
If it should be a Gnuplot issue, how could it be different whether  {/symbol l} or [ESC] l [ESC] is used in wxdraw2d or draw2d ?

Best regards
Rene'

**Comment by gunterkoenigsmann** [comment] 2015-12-16 22:45
Found it:
 - {/symbol I} takes the greek letter from the symbol font.
 - <ESC>I<ESC> takes it from the normal text font instead.
Seems like the symbol font is missing from gnuplot or broken.

Kind regards,

  Gunter.

**Closed** 2016-01-04 00:09 UTC

**Comment by ReneSci** [comment] 2016-01-04 08:50
How can it then be that the one works with wxdraw2d (only) and the other
works with draw2d (only) - I mean, it then seems lige both fonts are
present. Othervise it wouldent be possible to create the two plots ?

Best regards and Happy New Year
Rene'


2015-12-17 0:07 GMT+01:00 Gunter Königsman <notifications@github.com>:

**Comment by gunterkoenigsmann** [comment] 2016-01-05 18:34
Maxima always writes the commands it sends to gnuplot to a file named
maxout.gnuplot or similar in c:\Users\<your_username>. Perhaps there is
something suspicious in there that might help tracking down this bug...

But you are right: This is positively weird.

Kind regards,

     Gunter.

**Comment by ReneSci** [comment] 2016-01-07 15:50
Question: can it be made so either [esc] l [exc] or {\symbol l} will work
for both wxdraw2d and draw2d ?

Best regards
Rene'


2016-01-05 19:34 GMT+01:00 Gunter Königsman <notifications@github.com>:

**Comment by andrejv** [comment] 2016-01-08 10:38
I think this is not something which can be fixed in wxmaxima. The problem is that different gnuplot terminals are used. wxdraw2d uses the png terminal and draw2d uses the screen terminal. We can't control which is used because there are many options for each terminal (libpng, pngcairo, x11, qt, wx, windows,...) and each terminal supports different options.
