### ISSUE TITLE
MathML export should use mrow+mo instead of the mfenced element

### ISSUE THREAD

**Issue by fred-wang** [andrejv/wxmaxima#761] opened 2016-08-20 09:19 UTC
cc'ing @gunterkoenigsmann 

(x+1)^2 is exported as

    <math xmlns="http://www.w3.org/1998/Math/MathML">
      <msup>
        <mfenced separators="" open="(" close=")">
          <mrow>
            <mi>x</mi>
            <mi>+</mi>
            <mn>1</mn>
          </mrow>
        </mfenced>
        <mn>2</mn>
      </msup>
    </math>

It would be best to use the expanded form:

    <math xmlns="http://www.w3.org/1998/Math/MathML">
      <msup>
        <mrow>
          <mo>(</mo>
          <mrow>
            <mi>x</mi>
            <mi>+</mi>
            <mn>1</mn>
          </mrow>
          <mo>)</mo>
        </mrow>
        <mn>2</mn>
      </msup>
    </math>

Contrary to an urban legend, the mfenced element does not bring anything in term of semantics and it would be best to just use the expanded form to avoid many issues. See http://lists.w3.org/Archives/Public/www-math/2016Jul/0004.html for a proposal to get rid of that useless element.

Note in particular that Microsoft Word and LibreOffice support import of the expanded form with mrow+mo. LibreOffice also always export mrow+mo after https://bugs.documentfoundation.org/show_bug.cgi?id=66282#c5. Finally, as a comparison the Mathematica developers themselves say they always canonize into the mrow+mo form: http://lists.w3.org/Archives/Public/www-math/2016Jul/0017.html

**Comment by gunterkoenigsmann** [comment] 2016-08-20 10:52
For abs() and parentesis cells this works fine. But after the change

     matrix([1,2],[3,4]) 

outputs a table with small parenthesis around it, at least in firefox => Committing only the other types of cells.

**Comment by fred-wang** [comment] 2016-08-20 11:12
In debian testing, wxmaxima outputs:

    <math xmlns="http://www.w3.org/1998/Math/MathML">
      <mfenced open="(" close=")">
        <mtable>
          <mtr>
            <mtd>
              <mn>1</mn>
            </mtd>
            <mtd>
              <mn>2</mn>
            </mtd>
          </mtr>
          <mtr>
            <mtd>
              <mn>3</mn>
            </mtd>
            <mtd>
              <mn>4</mn>
            </mtd>
          </mtr>
        </mtable>
      </mfenced>
    </math>
    
Per the MathML spec, the expanded form would be (omitting implicit fence attributes):
    
    <math xmlns="http://www.w3.org/1998/Math/MathML">
      <mrow>
        <mo>(</mo>
        <mrow>
        <mtable>
          <mtr>
            <mtd>
              <mn>1</mn>
            </mtd>
            <mtd>
              <mn>2</mn>
            </mtd>
          </mtr>
          <mtr>
            <mtd>
              <mn>3</mn>
            </mtd>
            <mtd>
              <mn>4</mn>
            </mtd>
          </mtr>
        </mtable>
        </mrow>
        <mo>)</mo>
      </mrow>
    </math>

They render the same (with large parenthesis) for me in Gecko and WebKit.

**Comment by gunterkoenigsmann** [comment] 2016-08-20 11:22
My matrix cell code currently outputs:

<math xmlns="http://www.w3.org/1998/Math/MathML">
  <semantics>
    <mrow>
      <mo>(</mo>
      <mrow>
    <mtable>
          <mtr>
            <mtd>
              <mn>1</mn>
            </mtd>
            <mtd>
              <mn>2</mn>
            </mtd>
          </mtr>
          <mtr>
            <mtd>
              <mn>3</mn>
            </mtd>
            <mtd>
              <mn>4</mn>
          </mtd>
          </mtr>
    </mtable>
      </mrow>
      <mo>)</mo>
    </mrow>
    <annotation encoding="application/x-maxima">matrix([1,2],[3,4])</annotation>
  </semantics>
</math>

...but what I get out of this in Firefox 46.0.1 is the thing I have attached to this mail and which is consistent with rendering your test. My theory is that the firefox guys fell for the same urban myth as I did. But I might of course be utterly wrong in this respect.

Kind regards,

   Gunter.

**Comment by fred-wang** [comment] 2016-08-20 11:34
The output you provides render correctly (with large parenthesis) in both Gecko and WebKit so I suspect it's a problem with your setup. I'm surprised it would render better with mfenced though. Just a stupid question: Did you follow https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/Fonts ?

**Comment by gunterkoenigsmann** [comment] 2016-08-20 11:54
On 20.08.2016 13:34, Frédéric Wang wrote:
> The output you provides render correctly (with large parenthesis) in
> both Gecko and WebKit so I suspect it's a problem with your setup. I'm
> surprised it would render better with mfenced though. 
Half of wxMaxima has been fine-tuned a hundred times to find a equilibrium between correctness and the least surprise for our users. In most cases we have been able to provide both. Let's hope that this is a place we can reach such a point in. Did verify another time (see the attached screen shot): mfenced works fine for me.

A thing I didn't find a solution for that both MS Word 2007 and Firefox supported and that wasn't deprecated was the output of the following command:

        declare(x,complex);conjugate(x);

Don't know what to do about this, neither.
> Just a stupid
> question: Did you follow
> https://developer.mozilla.org/en-US/docs/Mozilla/MathML_Project/Fonts ?
>
The question is good: Without troubleshooting a problem cannot be resolved. But the font is installed on my system; Requiring all users to install additional things manually in order to make matrices work and to manually find out that they need to would sound like a showstopper to me, anyway so if this would be the problem we really would need an excellent workaround.

Kind regards,

   Gunter.

**Comment by fred-wang** [comment] 2016-08-20 12:41
mfenced and its expanded form should render the same in Gecko as specified in the MathML recommendation. If not then that's a bug and it seems that you should report it to Mozilla tracker instead of trying to workaround  it for your specific setup. But actually the font installation is irrelevant (if it is not installed they may render bad in both forms) so I still can't explain why you see it differently (and I did not find your screenshots).

Note that mfenced may render worse than its expanded form in WebKit. And features like "Find" or screen reading won't work with mfenced fences. But it seems that you did not test all of these.

>  declare(x,complex);conjugate(x); 

I see `<math xmlns="http://www.w3.org/1998/Math/MathML"><mover accent="true"><mi>x</mi><mo>&#x00AF;</mo></mover></math>` and it renders correctly for me. Not sure how it is related to that bug.

**Comment by gunterkoenigsmann** [comment] 2016-08-20 13:19
> 
> Note that mfenced may render worse than its expanded form in WebKit. And
> features like "Find" or screen reading won't work with mfenced fences.
> But it seems that you did not test all of these.
> 

This is correct: I don't own a browser that uses webkit - and I wouldn't
have expected that "Find" not working in equations would have been
caused by my actions.


Will file the bug when bugzilla is up again. But it might be the case
that for the next few years "stable" versions of debian and ubuntu will
run with broken browsers.

>     declare(x,complex);conjugate(x);
> 
> I see |<math xmlns="http://www.w3.org/1998/Math/MathML"><mover
> accent="true"><mi>x</mi><mo>&#x00AF;</mo></mover></math>| and it renders
> correctly for me. Not sure how it is related to that bug.
> 

It renders correctly. But I was always told that this way of describing
an overline is deprecated...

Kind regards,

 Gunter.

**Comment by gunterkoenigsmann** [comment] 2016-08-20 13:24
The scheduled downtime of Bugzilla was shorter than I thought:  https://bugzilla.mozilla.org/show_bug.cgi?id=1296857

**Comment by fred-wang** [comment] 2016-08-20 14:45
> Will file the bug when bugzilla is up again. But it might be the case that for the next few years "stable" versions of debian and ubuntu will run with broken browsers.

Thanks. As I said on the bug entry this is a known bug with MathML-only XML file. I was testing with HTML files thus the difference I get. So it does not seem a big concern in practice since virtually everybody uses MathML in HTML Web pages and not in a  standalone XML file.

> It renders correctly. But I was always told that this way of describing an overline is deprecated... 

It is recommended presentation MathML markup which is supported by web engines, Microsoft Word or Office. (It is different from content MathML)

**Comment by gunterkoenigsmann** [comment] 2016-08-20 16:03
Resolved with commit 01c713d86a80f3f13de71254a079501922ff7a82.

**Closed by gunterkoenigsmann** 2016-08-20 16:03 UTC

**Comment by gunterkoenigsmann** [comment] 2016-08-20 16:17
Only to make sure: Is the following correct?

<?xml version="1.0" encoding="utf-8"?>
<math xmlns="http://www.w3.org/1998/Math/MathML">
  <semantics>
    <mrow>
    <mo>(</mo>
    <mrow>
      <mtable>
        <mtr>
          <mtd>
            <mo>|</mo>
            <mrow>
              <mi>a</mi>
              <mi>+</mi>
              <mn>1</mn>
            </mrow>
            <mo>|</mo>
          </mtd>
          <mtd>
            <mo>|</mo>
            <mrow>
              <mi>b</mi>
              <mi>+</mi>
              <mn>1</mn>
            </mrow>
            <mo>|</mo>
          </mtd>
        </mtr>
        <mtr>
          <mtd>
            <mo>|</mo>
            <mrow>
              <mi>c</mi>
              <mi>+</mi>
              <mn>1</mn>
            </mrow>
            <mo>|</mo>
          </mtd>
          <mtd>
            <mo>|</mo>
            <mrow>
              <mi>d</mi>
              <mi>+</mi>
              <mn>1</mn>
            </mrow>
            <mo>|</mo>
          </mtd>
        </mtr>
      </mtable>
    </mrow>
    <mo>)</mo>
    </mrow>
    <annotation encoding="application/x-maxima">matrix([abs(a+1),abs(b+1)],[abs(c+1),abs(d+1)])</annotation>
  </semantics>
</math>

Firefox seems to like it. http://www.wiris.com/editor/demo/en/mathml-latex.html chokes on it, though.

Thanks a lot,
and kind regards,

    Gunter.

**Comment by fred-wang** [comment] 2016-08-20 16:35
> Only to make sure: Is the following correct?

Yes, it is.

>  http://www.wiris.com/editor/demo/en/mathml-latex.html chokes on it, though.

That seems to be a bug in WIRIS then :-(

**Comment by fred-wang** [comment] 2016-08-20 19:28
Some of the commits seems to replace mfenced with three children (one mo, one mrow and one mo). Note that these children should be wrapped inside an mrow to have the equivalence (this is the case in your examples, but I don't know if the mrow comes from a parent construction). Again see https://www.w3.org/TR/MathML3/chapter3.html#presm.mfenced
