### ISSUE TITLE
WxMaxima does not honour "maxima program" option

### ISSUE THREAD

**Issue by rend3r** [andrejv/wxmaxima#685] opened 2016-03-20 05:54 UTC
C:\maxima-current\bin\maxima.bat is path to maxima batch file.
"WxMaxima configuration - Maxima - Maxima program" option is set to C:\maxima-5.37post\bin\maxima.bat. Surely, i have not another instance of maxima there but WxMaxima successfully open maxima session (from C:\maxima-current\bin\maxima.bat) and work well evaluating documents.
Nothing changes if i set option to another [wrong] path.
wxMaxima version: 15.8.0
Maxima version: branch_5_37_base_489_gb2332bc_dirty
Maxima build date: 2016-02-12 16:33:10
Host type: i686-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.3.2
Nightly wxMaxima build (20.03.16) + maxima-clisp-sbcl-current.exe

**Comment by rend3r** [comment] 2016-03-20 06:02
>System type: Win32 6.1.7601 (Service Pack 1) X86
It's x64 but wxbuild_info() does not think so.

**Comment by andrejv** [comment] 2016-03-20 14:30
This is by desing.

If wxmaxima is installed as part of maxima, then it always uses the maxima binary which included it.

**Comment by rend3r** [comment] 2016-03-20 15:55
@andrejv 
Can you add some notes about it like about additional parameters for maxima? It's confusing now.

**Comment by andrejv** [comment] 2016-03-20 15:58
The options to set the maxima programs should be disabled if it is not used. Maybe this was removed with the changes to the configuration dialog.

**Comment by gunterkoenigsmann** [comment] 2016-03-24 20:07
Did accidentally close this issue. But it seems like I have actually resolved it for windows: On this system wxMaxima now takes the directory its executable lies in, appends a "../bin/maxima.bat" and canonifies the result in order to eliminate the "..".

The question now is if the result on a mac or linux computer is as intended:
Don't have a mac to test and on my linux box the contents of the text box reads "maxima" and is editable even if an executable named "maxima" can be found in my system's search path.

**Comment by rend3r** [comment] 2017-03-06 23:03
@gunterkoenigsmann 
Could you make this option active again in MSW build? I understand how many undesirable side effects this change may lead when maxima.bat is erroneously edited or wrongly placed.
As for me, it's ok when wxMaxima just kicking maxima.bat even if it's completely broken. My idea is divide current batch file to the bunch of small files - different lisps, lisp options and so on. In current state maxima.bat is rather complicated due legacy (some constructions for xmaxima only) and tricky hacks for windows batch shell.

**Closed** 2017-03-07 07:29 UTC
