### ISSUE TITLE
SBCL doesn't correctly save lisp files

### ISSUE THREAD

**Issue by epiparo** [andrejv/wxmaxima#612] opened 2015-11-11 17:13 UTC
I used to build libraries of functions and constants in order to simplify the notebooks. However when I tried to update a library with SBCL Maxima, I obtained the following error:

> #<FUNCTION delim-err> cannot be printed readably.
> Automatically continuing.
> To enable the Lisp debugger set *debugger-hook* to nil.

and the resulting lisp file corrupted. The CLISP version instead works.
PLEASE FIX IT!
-------------------------------------------------------------
wxMaxima version: 15.8.2
Maxima version: 5.37.2
Maxima build date: 2015-09-18 21:03:17
Host type: i686-pc-mingw32
System type: Win32 6.2.9200 X86
Lisp implementation type: SBCL
Lisp implementation version: 1.2.7
-------------------------------------------------------------

![libreria](https://cloud.githubusercontent.com/assets/15803346/11097468/e5bc272c-889f-11e5-91cf-e1ba4c464e92.png)

**Comment by gunterkoenigsmann** [comment] 2015-11-11 18:40
This is a bug in maxima, not in wxmaxima. But there is something I know 
of that you can test:



Could you create a file named

c:\users\<your username>\.sbclrc

and fill it with the following line of text?

            (setf sb-impl::default-external-format :utf-8)

If this fixes the problem the next major release of maxima will contain 
a bugfix for the problem you have found.

**Comment by epiparo** [comment] 2015-11-11 19:20
Unfortunately, It seems not working...

**Comment by gunterkoenigsmann** [comment] 2015-11-11 19:53
Then three more things before I give up and ask you to report the problem at the bug tracker or the mailing list of http://maxima.sourceforge.net instead:
 * What happens if you type in

     ü=1;

 * What is the output of

     x=1;
     :lisp (sb-impl::userinit-pathname)

 * Is the problem still reproducible if you use only plain english ascii characters in your calculation?

Thanks a lot,
and kind regards,

     Gunter.

**Comment by epiparo** [comment] 2015-11-11 20:38
With:
ü=1;
program hangs...
%i) x=1;
      :lisp (sb-impl::userinit-pathname)
%o) x=1
       C:/Users/Edoardo/.sbclrc

**Comment by epiparo** [comment] 2015-11-11 20:44
With plain english ascii characters the problem is still reproducible:
![immagine 3](https://cloud.githubusercontent.com/assets/15803346/11102537/5f7811bc-88bd-11e5-8ee9-fa8cfea0f96f.png)

**Comment by gunterkoenigsmann** [comment] 2015-11-11 20:50
On Mi, Nov 11, 2015 at 9:38 , epiparo <notifications@github.com> wrote:
> With:
> ü=1;
> program hangs...
> 
This means that your sbcl didn't find the .sbclrc containing the line

     (setf sb-impl::default-external-format :utf-8)


> %i) x=1;
> :lisp (sb-impl::userinit-pathname)
> %o) x=1
> C:/Users/Edoardo/.sbclrc
> 

This means that the sbcl your maxima is based on expects to find the 
.sbclrc file here:

C:/Users/Edoardo/.sbclrc

Since I assume you already tried to put the file there...

...could it be that your copy of windows has
 * marked the file to be a text file by adding a .txt to its name 
making it C:/Users/Edoardo/.sbclrc.txt
 * and then has decided not to show the additional .txt since it is a 
known file extension?

Windows seems to actively try to hinder users from creating files whose 
name begins with "."
The only way I found to create such a file was
 * to tell the windows explorer in it's folder options to show the file 
name endings for known files, too
 * then to create a sbclrc.txt file
 * to copy-and-paste the contents into this file
 * and then to rename it to .sbclrc

Cannot think of another reason why sbcl won't find the file on your 
computer. But - windows seems to be hard to debug at all times, 
sometimes. At least to me as an outsider.

**Comment by gunterkoenigsmann** [comment] 2015-11-11 20:54
On Mi, Nov 11, 2015 at 9:44 , epiparo <notifications@github.com> wrote:
> With plain english ascii characters the problem is still reproducible:
> 
Then I am no more sure if you encountered an UTF8-Problem => I am 
afraid if you want help you might need to ask the maxima project 
instead.

Will probably have no internet connection for the next 5 days.

Kind regards,

 Gunter.

**Comment by epiparo** [comment] 2015-11-11 21:08
I'have correctly renamed .sbclrc file.
However wxMaxima again hangs on:

> ü=1;

and if restarted gives the following messages:

> Message from maxima's stderr stream: 
> ; file: C:/Users/Edoardo/.sbclrc
> ; in: SETF SB-IMPL::DEFAULT-EXTERNAL-FORMAT
> ;     (SETF SB-IMPL::DEFAULT-EXTERNAL-FORMAT :UTF-8)
> ; ==>
> ;   (SETQ SB-IMPL::DEFAULT-EXTERNAL-FORMAT :UTF-8)
> ; 
> ; caught WARNING:
> ;   undefined variable: SB-IMPL::DEFAULT-EXTERNAL-FORMAT
> ; 
> ; compilation unit finished
> ;   Undefined variable:
> ;     SB-IMPL::DEFAULT-EXTERNAL-FORMAT
> ;   caught 1 WARNING condition

**Comment by gunterkoenigsmann** [comment] 2015-11-11 21:16
Ok... ...this error message looks like I was wrong about what the file 
should contain.

Try to fill it with the command

    (setf sb-impl::*default-external-format* :utf-8)

instead. Hope that this resolves the problem.

Kind regards,

      Gunter.

**Comment by epiparo** [comment] 2015-11-11 21:38
The troubles with non standard characters are solved but not that with LISP saving...
I will try with Maxima support...
Thank you for all!
Best regards
Edoardo

**Comment by robert-dodier** [comment] 2015-11-14 16:06
This bug was reported to the Maxima bug tracker as #3045 and fixed by Maxima commit 4b6c2df. This bug report can be closed now.

**Closed** 2015-12-12 20:03 UTC
