### ISSUE TITLE
Output of "solve([(x-x0)/(x1-x0)=s],[x]);" missing parentheses .

### ISSUE THREAD

**Issue by sagasm** [andrejv/wxmaxima#688] opened 2016-03-21 06:13 UTC
intput: solve([(x-x0)/(x1-x0)=s],[x]);
output: [x=s x1+1-s x0]

wxMaxima version: 15.8.0
Maxima version: 5.37.3_5_g8106b41_dirty
Maxima build date: 2015-11-14 16:49:58
Host type: i686-w64-mingw32
System type: 
gcc -mno-cygwin -g -O2 -W -Wswitch -Wcomment -Wpointer-arith -Wimplicit -Wreturn-type -Wmissing-declarations -Wno-sign-compare -Wno-format-nonliteral -O2 -fexpensive-optimizations -falign-functions=4 -D_WIN32 -DENABLE_UNICODE -I/usr/local/include -DDYNAMIC_FFI -I. -L/usr/local/lib  -lintl /usr/local/lib/libreadline.dll.a -L/usr/local/lib -ltermcap /usr/local/lib/libavcall.a /usr/local/lib/libcallback.a -luser32 -lws2_32 -lole32 -loleaut32 -luuid -liconv -L/usr/local/lib -lsigsegv libgnu_cl.a 
SAFETY=0 HEAPCODES STANDARD_HEAPCODES GENERATIONAL_GC SPVW_BLOCKS SPVW_MIXED TRIVIALMAP_MEMORY
libsigsegv 2.8
libiconv 1.13
libreadline 6.0 GNU C 3.4.5 (mingw-vista special r3) PC/386
Lisp implementation type: CLISP
Lisp implementation version: 2.49 (2010-07-07) (built on 158234.vs.webtropia.com [127.12.34.56])

**Comment by gunterkoenigsmann** [comment] 2016-03-21 06:17
If the problem was caused by missing parenthesis I hope the current nightly build (http://andrejv.github.io/wxmaxima/develop.html#WindowsNightly) will fix it: Did spend loads of time searching for missing parenthesis in the last months and at one point decided that it is time to delegate this task to wxMaxima.

**Comment by gunterkoenigsmann** [comment] 2016-03-21 06:20
Seems like we need a new release urgently: On the current nightly build of wxMaxima using a maxima version I compiled myself from git this error cannot be reproduced, neither.

**Comment by sagasm** [comment] 2016-03-21 07:36
So which version now I can use.

**Comment by rend3r** [comment] 2016-03-22 20:24
@sagasm 
I use http://wolfgang.dautermann.at/maxima/maxima-clisp-sbcl-current.exe (with SBCL) and nightly wxMaxima builds http://wolfgang.dautermann.at/maxima/wxmaxima-daily-win.zip and cannot reproduce the issue.

**Comment by sagasm** [comment] 2016-03-23 01:29
Use package from these two address,still missing parentheses.

**Comment by rend3r** [comment] 2016-03-23 06:15
Did you switch to sbcl in wxMaxima configuration (additional parameters for maxima: -l sbcl)?

**Comment by sagasm** [comment] 2016-03-23 07:15
With  -l sbcl,sbcl.exe crashed.

**Comment by sagasm** [comment] 2016-04-14 02:41
Also I tried wxMaxima this version:
wxMaxima version: 16.4.1
Maxima version: 5.38.0
Maxima build date: 2016-04-09 15:18:17
Host type: i686-pc-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86-64
Lisp implementation type: SBCL
Lisp implementation version: 1.3.4

Input: a*(ab+c);
but the output displayed was:
(%o1) a*c+ab
If I copy the output here it change to:
(%o1) a*(c+ab)

Raw XML monitor:
a*(ab+c);


MAXIMA RESPONSE:

<mth>
  <lbl>(%o4) </lbl>
  <v>a</v>
  <h>*</h>
  <p>
    <v>c</v>
    <v>+</v>
    <v>ab</v>
    </p>
   </mth>
<PROMPT-P/>(%i5) <PROMPT-S/>

**Comment by rend3r** [comment] 2016-04-14 03:56
> Input: a * (ab+c);
> but the output displayed was:
> (%o1) a c+ab

Very interesting. Seems it's maxima bug
```
(%i1) a * (ab+c);
(%o1) a*(c+ab)
(%o2) expand(%);
(%o2) a*c+a*ab
```
Works as expected.

>If I copy the output here it changes to:
>(%o1) a * (c+ab)

Copypaste works as charm for input and output. Definitely wxMaxima regression

wxMaxima version: 15.8.0
Maxima version: branch_5_37_base_489_gb2332bc_dirty
Maxima build date: 2016-02-12 16:33:10
Host type: i686-w64-mingw32
System type: Win32 6.1.7601 (Service Pack 1) X86
Lisp implementation type: SBCL
Lisp implementation version: 1.3.2
Old nightly build near https://github.com/andrejv/wxmaxima/commit/77e79ec78722ac08de80f68a368b6e8a17bbc40b

Which installer do you use - maxima-clisp-sbcl-5.38.0.exe or maxima-sbcl-5.38.0-win64.exe?

**Comment by sagasm** [comment] 2016-04-14 04:05
I tried all versions include maxima 5.37.0,5.37.1,5.37.2,5.37.3 to 5.38.0 .

**Comment by rend3r** [comment] 2016-04-14 04:09
@sagasm 
>I tried all versions include maxima 5.37.0,5.37.1,5.37.2,5.37.3 to 5.38.0

What's the version at the screenshot?

**Comment by sagasm** [comment] 2016-04-14 04:09
http://netcologne.dl.sourceforge.net/project/maxima/Maxima-Windows/5.38.0-Windows/maxima-sbcl-5.38.0-win64.exe

**Comment by sagasm** [comment] 2016-04-16 06:47
Intresting,I tried maxima 5.37.2 at Fedora 23,no problem at all.

**Comment by gunterkoenigsmann** [comment] 2017-11-25 16:53
This error no more occurs with the combination of the newest maxima and the newest wxMaxima => closing it.

**Closed by gunterkoenigsmann** 2017-11-25 16:53 UTC
