### ISSUE TITLE
A bug in plotting abs function ?

### ISSUE THREAD

**Issue by triplopinco** [andrejv/wxmaxima#734] opened 2016-06-20 07:58 UTC
The following code

f(x):=abs(x+%i)^2;
wxplot2d(realpart(f(x)),[x,-1,1]);

produce a plot with negative value.
However f(x) gives (correctly) 1

**Comment by gunterkoenigsmann** [comment] 2016-06-20 17:22
This seems to be caused by or at least to have to do with the difference
between abs() and cabs(). Unfortunately I don't know in detail what the
cause is. But if you want to the experts from the maxima-discuss mailing
list at https://maxima.sourceforge.net will be able to answer your
questions.

Will close this ticket here, not because it is invalid or because I'm
not interested in what has happened but because I think that the maxima
project can provide more accurate answers than I can.

Kind regards,
Gunter.

**Closed** 2016-06-20 17:22 UTC
